# Etapa 1: Construcción de Angular
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production

# Etapa 2: Servidor Nginx interno para los archivos estáticos
FROM nginx:alpine
# Copiamos la build de Angular a la carpeta que sirve Nginx
# NOTA: Cambia "frontend" si el angular.json de tu proyecto lo saca a otra ruta
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
# Copiamos una configuración básica de Nginx para SPA (Single Page Application)
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
