module.exports = {
  // Vocabulary: Nouns, Adjectives, Adverbs, Domain terms
  "trabajo": "treball", "trabajos": "treballs",
  "apoyo": "suport", "apoyos": "suports",
  "aprendizaje": "aprenentatge", "aprendizajes": "aprenentatges",
  "reto": "repte", "retos": "reptes",
  "salón": "saló", "salones": "salons",
  "peluquería": "perruqueria", "peluquerías": "perruqueries",
  "estética": "estètica", "estético": "estètic", "estéticos": "estètics", "estéticas": "estètiques",
  "belleza": "bellesa",
  "maquillaje": "maquillatge", "maquillajes": "maquillatges",
  "masaje": "massatge", "masajes": "massatges",
  "manicura": "manicura", "manicuras": "manicures",
  "pedicura": "pedicura", "pedicuras": "pedicures",
  "depilación": "depilació", "depilaciones": "depilacions",
  "coloración": "coloració", "coloraciones": "coloracions",
  "decoloración": "decoloració", "decoloraciones": "decoloracions",
  "corte": "tall", "cortes": "talls",
  "peinado": "pentinat", "peinados": "pentinats",
  "recogido": "recollit", "recogidos": "recollits",
  "marcado": "marcat", "marcados": "marcats",
  "ondulación": "ondulació", "ondulaciones": "ondulacions",
  "alisado": "allissat", "alisados": "allissats",
  "secado": "assecatge", "lavado": "rentat", "aclarado": "esbandit",
  "cabello": "cabell", "cabellos": "cabells",
  "cuero": "cuir", "cabelludo": "cabellut",
  "pelo": "pèl", "pelos": "pèls",
  "vello": "pèl", "vellos": "pèls", "superfluo": "superflu",
  "piel": "pell", "pieles": "pells",
  "uña": "ungla", "uñas": "ungles",
  "cutícula": "cutícula", "cutículas": "cutícules",
  "ceja": "cella", "cejas": "celles",
  "pestaña": "pestanya", "pestañas": "pestanyes",
  "ojo": "ull", "ojos": "ulls",
  "boca": "boca", "bocas": "boques",
  "labio": "llavi", "labios": "llavis", "labial": "barra de llavis", "labiales": "barres de llavis",
  "cara": "cara", "caras": "cares",
  "rostre": "rostre", "rostros": "rostres",
  "mano": "mà", "manos": "mans",
  "pie": "peu", "pies": "peus",
  "pierna": "cama", "piernas": "cames",
  "brazo": "braç", "brazos": "braços",
  "espalda": "esquena", "cuello": "coll", "hombro": "muscle", "hombros": "muscles",
  "ropa": "roba", "calzado": "calçat", "uniforme": "uniforme", "uniformes": "uniformes",
  "toalla": "tovallola", "toallas": "tovalloles", "toallitas": "tovalloletes",
  "bata": "bata", "batas": "bates",
  "capa": "capa", "capas": "capes",
  "peine": "pinta", "peines": "pintes",
  "cepillo": "raspall", "cepillos": "raspalls",
  "tijera": "tisora", "tijeras": "tisores",
  "secador": "assecador", "secadores": "assecadors",
  "plancha": "planxa", "planchas": "planxes",
  "tenacilla": "tenalla", "tenacillas": "tenalles",
  "rulo": "rulo", "rulos": "rulos",
  "molde": "motle", "moldes": "motles",
  "pinza": "pinca", "pinzas": "pinces",
  "paletina": "paletina", "paletinas": "paletines",
  "bol": "bol", "boles": "bols",
  "espejo": "espill", "espejos": "espills",
  "mesa": "taula", "mesas": "taules",
  "silla": "cadira", "sillas": "cadires",
  "sillón": "butaca", "sillones": "badires",
  "tocador": "tocador", "tocadores": "tocadors",
  "lavacabezas": "rentacaps",
  "camilla": "llitera", "camillas": "lliteres",
  "papel": "paper", "papeles": "papers",
  "aluminio": "alumini",
  "algodón": "cotó", "algodones": "cotons",
  "champú": "xampú", "champús": "xampús",
  "crema": "crema", "cremas": "cremes",
  "cera": "cera", "ceras": "ceres",
  "aceite": "oli", "aceites": "olis",
  "tinte": "tint", "tintes": "tints",
  "esmalte": "esmalt", "esmaltes": "esmalts",
  "lima": "llima", "limas": "llimes",
  "pulido": "polit", "pulidor": "polidor",
  "dureza": "duresa", "durezas": "dureses",
  "espátula": "espàtula", "espátulas": "espàtules",
  "banda": "banda", "bandas": "bandes",
  "guante": "guant", "guantes": "guants",
  "mascarilla": "mascareta", "mascarillas": "mascaretes",
  "vestuario": "vestidor", "vestuarios": "vestidors",
  "taller": "taller", "talleres": "tallers",
  "aula": "aula", "aulas": "aules",
  "almacén": "magatzem", "almacenes": "magatzems",
  "empresa": "empresa", "empresas": "empreses",
  "salud": "salut", "higiene": "higiene", "limpieza": "neteja",
  "seguridad": "seguretat", "prevención": "prevenció",
  "riesgo": "risc", "riesgos": "riscos",
  "incidencia": "incidència", "incidencias": "incidències",
  "error": "error", "errores": "errors",
  "queja": "queixa", "quejas": "queixes",
  "reclamación": "reclamació", "reclamaciones": "reclamacions",
  "satisfacción": "satisfacció", "conformidad": "conformitat",
  "calidad": "qualitat", "precio": "preu", "precios": "preus",
  "coste": "cost", "costes": "costos",
  "presupuesto": "pressupost", "presupuestos": "pressupostos",
  "ficha": "fitxa", "fichas": "fitxes",
  "formulario": "formulari", "formularios": "formularis",
  "guía": "guia", "guías": "guies",
  "manual": "manual", "manuales": "manuals",
  "folleto": "fullet", "folletos": "fullets",
  "cartel": "cartell", "carteles": "cartells",
  "póster": "pòster", "pósters": "pòsters",
  "informe": "informe", "informes": "informes",
  "registro": "registre", "registros": "registres",
  "diario": "diari", "diarios": "diaris",
  "portfolio": "portafoli", "portfolios": "portafolis",
  "rúbrica": "rúbrica", "rúbricas": "rúbriques",
  "escala": "escala", "escalas": "escales",
  "lista": "llista", "listas": "llistes",
  "plantilla": "plantilla", "plantillas": "plantilles",
  "tarjeta": "targeta", "tarjetas": "targetes",
  "banco": "banc", "bancos": "bancs",
  "juego": "joc", "juegos": "jocs",
  "red": "xarxa", "redes": "xarxes",
  "vídeo": "vídeo", "vídeos": "vídeos",
  "foto": "foto", "fotos": "fotos",
  "fotografía": "fotografia", "fotografías": "fotografies",
  "imagen": "imatge", "imágenes": "imatges",
  "audio": "àudio", "audios": "àudios",
  "página": "pàgina", "páginas": "pàgines",
  "enlace": "enllaç", "enlaces": "enllaços",
  "texto": "text", "textos": "textos",
  "frase": "frase", "frases": "frases",
  "palabra": "paraula", "palabras": "paraules",
  "mensaje": "missatge", "mensajes": "missatges",
  "carta": "carta", "cartas": "cartes",
  "correo": "correu", "correos": "correus",
  "cita": "cita", "citas": "cites",
  "agenda": "agenda", "agendas": "agendes",
  "horario": "horari", "horarios": "horaris",
  "tiempo": "temps", "tiempos": "temps",
  "hora": "hora", "horas": "hores",
  "minuto": "minut", "minutos": "minuts",
  "segundo": "segon", "segundos": "segons",
  "día": "dia", "días": "dies",
  "semana": "setmana", "semanas": "setmanes",
  "mes": "mes", "meses": "mesos",
  "año": "any", "años": "anys",
  "alumnado": "alumnat",
  "alumno": "alumne", "alumnos": "alumnes",
  "alumna": "alumna", "alumnas": "alumnes",
  "docente": "docent", "docentes": "docents",
  "profesor": "professor", "profesores": "professors",
  "profesora": "professora", "profesoras": "professores",
  "cliente": "client", "clientes": "clients",
  "clienta": "clienta", "clientas": "clientes",
  "persona": "persona", "personas": "persones",
  "compañero": "company", "compañeros": "companys",
  "compañera": "companya", "compañeras": "companyes",
  "pareja": "parella", "parejas": "parelles",
  "grupo": "grup", "grupos": "grups",
  "equipo": "equip", "equipos": "equips",
  "rol": "rol", "roles": "rols",
  "resíduo": "residu", "residuos": "residus",
  "basura": "brossa", "cubo": "cubell", "recipiente": "recipient", "recipientes": "recipients",
  "envase": "envàs", "envases": "envasos",
  "etiqueta": "etiqueta", "etiquetas": "etiquetes",
  "sombra": "ombra", "sombras": "ombres",
  "colorete": "coloret", "coloretes": "colorets",
  "pincel": "pinzell", "pinceles": "pinzells",
  "brocha": "brotxa", "brochas": "brotxes",
  "esponja": "esponja", "esponjas": "esponges",
  "borla": "borla", "borlas": "borles",
  "lápiz": "llapis", "lápices": "llapis",
  "máscara": "màscara", "máscaras": "màscares",
  "fondo": "fons", "fondos": "fons",
  "corrector": "corrector", "correctores": "correctors",
  "visagismo": "visatgisme",
  "tono": "to", "tonos": "tos",
  "matiz": "matís", "matices": "matisos",
  "mecha": "metxa", "mechas": "metxes",
  "reflejo": "reflex", "reflejos": "reflexos",
  "alergia": "al·lèrgia", "alergias": "al·lèrgies",
  "sensibilidad": "sensibilitat",
  "intolerancia": "intolerància",
  "reacción": "reacció", "reacciones": "reaccions",
  "prueba": "prova", "pruebas": "proves",
  "muestra": "mostra", "muestras": "mostres",
  "modelo": "model", "modelos": "models",
  "caso": "cas", "casos": "casos",
  "ejemplo": "exemple", "ejemplos": "exemples",
  "paso": "pas", "pasos": "pasos",
  "fase": "fase", "fases": "fases",
  "etapa": "etapa", "etapas": "etapes",
  "pauta": "pauta", "pautas": "pautes",
  "norma": "norma", "normas": "normes",
  "criterio": "criteri", "criterios": "criteris",
  "indicador": "indicador", "indicadores": "indicadors",
  "resultado": "resultat", "resultados": "resultats",
  "evidencia": "evidència", "evidencias": "evidències",
  "producto": "producte", "productos": "productes",
  "servicio": "servei", "servicios": "serveis",
  "atención": "atenció",
  "comunicación": "comunicació",
  "expresión": "expressió",
  "lenguaje": "llenguatge", "lenguajes": "llenguatges",
  "discurso": "discurs", "discursos": "discursos",
  "diálogo": "diàleg", "diálogos": "diàlegs",
  "debate": "debat", "debates": "debats",
  "entrevista": "entrevista", "entrevistas": "entrevistes",
  "encuesta": "enquesta", "encuestas": "enquestes",
  "pregunta": "pregunta", "preguntas": "preguntes",
  "respuesta": "resposta", "respuestas": "respostes",
  "duda": "dubte", "dudas": "dubtes",
  "acuerdo": "acord", "acuerdos": "acords",
  "conflicto": "conflicte", "conflictos": "conflictes",
  "opinión": "opinió", "opiniones": "opinions",
  "argumento": "argument", "argumentos": "arguments",
  "propuesta": "proposta", "propuestas": "propostes",
  "idea": "idea", "ideas": "idees",
  "objetivo": "objectiu", "objetivos": "objectius",
  "finalidad": "finalitat",
  "contenido": "contingut", "contenidos": "continguts",
  "competencia": "competència", "competencias": "competències",
  "destreza": "destresa", "destrezas": "destreses",
  "habilidad": "habilitat", "habilidades": "habilitats",
  "actitud": "actitud", "actitudes": "actituds",
  "valor": "valor", "valores": "valors",
  "respeto": "respecte",
  "empatía": "empatia",
  "asertividad": "assertivitat",
  "autonomía": "autonomia",
  "responsabilidad": "responsabilitat",
  "autoestima": "autoestima",
  "creatividad": "creativitat",
  "iniciativa": "iniciativa",
  "diversidad": "diversitat",
  "inclusión": "inclusió",
  "convivencia": "convivència",
  "deontología": "deontologia",
  "ética": "ètica",
  "legislación": "legislació",
  "derecho": "dret", "derechos": "drets",
  "deber": "deure", "deberes": "deures",
  "garantía": "garantia", "garantías": "garanties",
  "módulo": "mòdul", "módulos": "mòduls",
  "ciclo": "cicle", "ciclos": "cicles",
  "curso": "curs", "cursos": "cursos",
  "conexión": "connexió", "conexiones": "connexions",
  "relación": "relació", "relaciones": "relacions",
  "diferencia": "diferència", "diferencias": "diferències",
  "similitud": "similitud", "similitudes": "similituds",
  "cambio": "canvi", "cambios": "canvis",
  "evolución": "evolució",
  "historia": "història",
  "cultura": "cultura", "culturas": "cultures",
  "sociedad": "societat", "sociedades": "societats",
  "entorno": "entorn", "entornos": "entorns",
  "medio": "medi", "medios": "mitjans",
  "ambiente": "ambient", "ambientes": "ambients",
  "naturaleza": "naturalesa",
  "energía": "energia",
  "electricidad": "electricitat",
  "calor": "calor",
  "temperatura": "temperatura",
  "agua": "aigua",
  "aire": "aire",
  "materia": "matèria",
  "sustancia": "substància", "sustancias": "substàncies",
  "mezcla": "barreja", "mezclas": "barreges",
  "disolución": "dissolució", "disoluciones": "dissolucions",
  "reacción": "reacció", "reacciones": "reaccions",
  "oxidación": "oxidació",
  "combustión": "combustió",
  "contaminación": "contaminació",
  "reciclaje": "reciclatge",
  "sostenibilidad": "sostenibilitat",
  "consumo": "consum",
  "ahorro": "estalvi",
  "gasto": "despesa", "gastos": "despeses",
  "magnitud": "magnitud", "magnitudes": "magnituds",
  "unidad": "unitat", "unidades": "unitats",
  "medida": "mesura", "medidas": "mesures",
  "cantidad": "quantitat", "cantidades": "quantitats",
  "peso": "pes", "pesos": "pesos",
  "masa": "massa",
  "volumen": "volum", "volúmenes": "volums",
  "longitud": "longitud",
  "superficie": "superfície", "superficies": "superfícies",
  "gráfico": "gràfic", "gráficos": "gràfics",
  "tabla": "taula", "tablas": "taules",
  "función": "funció", "funciones": "funcions",
  "porcentaje": "percentatge", "porcentajes": "percentatges",
  "proporción": "proporció", "proporciones": "proporcions",
  "operación": "operació", "operaciones": "operacions",
  "problema": "problema", "problemas": "problemes",
  "cálculo": "càlcul", "cálculos": "càlculs",
  "número": "número", "números": "números",
  "cifra": "xifra", "cifras": "xifres",
  "dato": "dada", "datos": "dades",
  "estadística": "estadística",
  "probabilidad": "probabilitat", "probabilidades": "probabilitats",

  // Adjectives
  "básico": "bàsic", "básica": "bàsica", "básicos": "bàsics", "básicas": "bàsiques",
  "técnico": "tècnic", "técnica": "tècnica", "técnicos": "tècnics", "técnicas": "tècniques",
  "práctico": "pràctic", "práctica": "pràctica", "prácticos": "pràctics", "prácticas": "pràctiques",
  "físico": "físic", "física": "física", "físicos": "físics", "físicas": "físiques",
  "químico": "químic", "química": "química", "químicos": "químics", "químicas": "químiques",
  "eléctrico": "elèctric", "eléctrica": "elèctrica", "eléctricos": "elèctrics", "eléctricas": "elèctriques",
  "térmico": "tèrmic", "térmica": "tèrmica", "térmicos": "tèrmics", "térmicas": "tèrmiques",
  "mecánico": "mecànic", "mecánica": "mecànica", "mecánicos": "mecànics", "mecánicas": "mecàniques",
  "artístico": "artístic", "artística": "artística", "artísticos": "artístics", "artísticas": "artístiques",
  "histórico": "històric", "histórica": "històrica", "históricos": "històrics", "históricas": "històriques",
  "tecnológico": "tecnològic", "tecnológica": "tecnològica", "tecnológicos": "tecnològics", "tecnológicas": "tecnològiques",
  "científico": "científic", "científica": "científica", "científicos": "científics", "científicas": "científiques",
  "matemático": "matemàtic", "matemática": "matemàtica", "matemáticos": "matemàtics", "matemáticas": "matemàtiques",
  "lingüístico": "lingüístic", "lingüística": "lingüística", "lingüísticos": "lingüístics", "lingüísticas": "lingüístiques",
  "ergonómico": "ergonòmic", "ergonómica": "ergonòmica", "ergonómicos": "ergonòmics", "ergonómicas": "ergonòmiques",
  "ecológico": "ecològic", "ecológica": "ecològica", "ecológicos": "ecològics", "ecológicas": "ecològiques",
  "académico": "acadèmic", "académica": "acadèmica", "académicos": "acadèmics", "académicas": "acadèmiques",
  "clínico": "clínic", "clínica": "clínica", "clínicos": "clínics", "clínicas": "clíniques",
  "dermatológico": "dermatològic", "dermatológica": "dermatològica", "dermatológicos": "dermatològics", "dermatológicas": "dermatològiques",
  "específico": "específic", "específica": "específica", "específicos": "específics", "específicas": "específiques",
  "higiénico": "higiènic", "higiénica": "higiènica", "higiénicos": "higiènics", "higiénicas": "higièniques",
  "armónico": "harmònic", "armónica": "harmònica", "armónicos": "harmònics", "armónicas": "harmòniques",
  "simétrico": "simètric", "simétrica": "simètrica", "simétricos": "simètrics", "simétricas": "simètriques",
  "lógico": "lògic", "lógica": "lògica", "lógicos": "lògics", "lógicas": "lògiques",
  "crítico": "crític", "crítica": "crítica", "críticos": "crítics", "críticas": "crítiques",
  "clásico": "clàssic", "clásica": "clàssica", "clásicos": "clàssics", "clásicas": "clàssiques",
  "auténtico": "autèntic", "auténtica": "autèntica", "auténticos": "autèntics", "auténticas": "autèntiques",
  "genérico": "genèric", "genérica": "genèrica", "genéricos": "genèrics", "genéricas": "genèriques",
  "público": "públic", "pública": "pública", "públicos": "públics", "públicas": "públiques",
  "profesional": "professional", "profesionales": "professionals",
  "personal": "personal", "personales": "personals",
  "laboral": "laboral", "laborales": "laborals",
  "digital": "digital", "digitales": "digitals",
  "cultural": "cultural", "culturales": "culturals",
  "social": "social", "sociales": "socials",
  "sensorial": "sensorial", "sensoriales": "sensorials",
  "general": "general", "generales": "generals",
  "natural": "natural", "naturales": "naturals",
  "visual": "visual", "visuales": "visuals",
  "actual": "actual", "actuales": "actuals",
  "individual": "individual", "individuales": "individuals",
  "puntual": "puntual", "puntuales": "puntuals",
  "real": "real", "reales": "reals",
  "formal": "formal", "formales": "formals",
  "comercial": "comercial", "comerciales": "comercials",
  "curricular": "curricular", "curriculares": "curriculars",
  "capilar": "capil·lar", "capilares": "capil·lars",
  "similar": "similar", "similares": "similars",
  "familiar": "familiar", "familiares": "familiars",
  "fácil": "fàcil", "fáciles": "fàcils",
  "difícil": "difícil", "difíciles": "difícils",
  "útil": "útil", "útiles": "útils",
  "ágil": "àgil", "ágiles": "àgils",
  "hábil": "hàbil", "hábiles": "hàbils",
  "posible": "possible", "posibles": "possibles",
  "imposible": "impossible", "imposibles": "impossibles",
  "visible": "visible", "visibles": "visibles",
  "invisible": "invisible", "invisibles": "invisibles",
  "sensible": "sensible", "sensibles": "sensibles",
  "accesible": "accessible", "accesibles": "accessibles",
  "responsable": "responsable", "responsables": "responsables",
  "sostenible": "sostenible", "sostenibles": "sostenibles",
  "amable": "amable", "amables": "amables",
  "favorable": "favorable", "favorables": "favorables",
  "adecuado": "adequat", "adecuada": "adequada", "adecuados": "adequats", "adecuadas": "adequades",
  "inadecuado": "inadequat", "inadecuada": "inadequada", "inadecuados": "inadequats", "inadecuadas": "inadequades",
  "apropiado": "apropiat", "apropiada": "apropiada", "apropiados": "apropiats", "apropiadas": "apropiades",
  "correcto": "correcte", "correcta": "correcta", "correctos": "correctes", "correctas": "correctes",
  "incorrecto": "incorrecte", "incorrecta": "incorrecta", "incorrectos": "incorrectes", "incorrectas": "incorrectes",
  "completo": "complet", "completa": "completa", "completos": "complets", "completas": "completes",
  "incompleto": "incomplet", "incompleta": "incompleta", "incompletos": "incomplets", "incompletas": "incompletes",
  "directo": "directe", "directa": "directa", "directos": "directes", "directas": "directes",
  "indirecto": "indirecte", "indirecta": "indirecta", "indirectos": "indirectes", "indirectas": "indirectes",
  "seguro": "segur", "segura": "segura", "seguros": "segurs", "seguras": "segures",
  "inseguro": "insegur", "insegura": "insegura", "inseguros": "insegurs", "inseguras": "insegures",
  "claro": "clar", "clara": "clara", "claros": "clars", "claras": "clares",
  "limpio": "net", "limpia": "neta", "limpios": "nets", "limpias": "netes",
  "sucio": "brut", "sucia": "bruta", "sucios": "bruts", "sucias": "brutes",
  "seco": "sec", "seca": "seca", "secos": "secs", "secas": "seques",
  "mojado": "mullat", "mojada": "mullada", "mojados": "mullats", "mojadas": "mullades",
  "húmedo": "humit", "húmeda": "humida", "húmedos": "humits", "húmedas": "humides",
  "nuevo": "nou", "nueva": "nova", "nuevos": "nous", "nuevas": "noves",
  "viejo": "vell", "vieja": "vella", "viejos": "vells", "viejas": "velles",
  "antiguo": "antic", "antigua": "antiga", "antiguos": "antics", "antiguas": "antigues",
  "moderno": "modern", "moderna": "moderna", "modernos": "moderns", "modernas": "modernes",
  "bueno": "bo", "buena": "bona", "buenos": "bons", "buenas": "bones",
  "malo": "dolent", "mala": "dolenta", "malos": "dolents", "malas": "dolentes",
  "gran": "gran", "grande": "gran", "grandes": "grans",
  "pequeño": "xicotet", "pequeña": "xicoteta", "pequeños": "xicotets", "pequeñas": "xicotetes",
  "corto": "curt", "corta": "curta", "cortos": "curts", "cortas": "curtes",
  "largo": "llarg", "larga": "llarga", "largos": "llargs", "largas": "llargues",
  "alto": "alt", "alta": "alta", "altos": "alts", "altas": "altes",
  "bajo": "baix", "baja": "baixa", "bajos": "baixos", "bajas": "baixes",
  "rápido": "ràpid", "rápida": "ràpida", "rápicos": "ràpids", "rápidas": "ràpides",
  "lento": "lent", "lenta": "lenta", "lentos": "lents", "lentas": "lentes",
  "fuerte": "fort", "fuerte": "fort", "fuertes": "forts",
  "débil": "feble", "débiles": "febles",
  "joven": "jove", "jóvenes": "joves",
  "mayor": "major", "mayores": "majors",
  "menor": "menor", "menores": "menors",
  "mejor": "millor", "mejores": "millors",
  "peor": "pitjor", "peores": "pitjors",
  "primer": "primer", "primero": "primer", "primera": "primera", "primeros": "primers", "primeras": "primeres",
  "segundo": "segon", "segunda": "segona", "segundos": "segons", "segundas": "segones",
  "tercero": "tercer", "tercera": "tercera", "terceros": "tercers", "terceras": "terceres",
  "último": "últim", "última": "última", "últimos": "últims", "últimas": "últimes",
  "próximo": "pròxim", "próxima": "pròxima", "próximos": "pròxims", "próximas": "pròximes",
  "siguiente": "següent", "siguientes": "següents",
  "previo": "previ", "previa": "prèvia", "previos": "previs", "previas": "prèvies",
  "posterior": "posterior", "posteriores": "posteriors",
  "ficticio": "fictici", "ficticia": "fictícia", "ficticios": "ficticis", "ficticias": "fictícies",
  "bilingüe": "bilingüe", "bilingües": "bilingües",
  "inclusivo": "inclusiu", "inclusiva": "inclusiva", "inclusivos": "inclusius", "inclusivas": "inclusives",
  "creativo": "creatiu", "creativa": "creativa", "creativos": "creatius", "creativas": "creatives",
  "formativo": "formatiu", "formativa": "formativa", "formativos": "formatius", "formativas": "formatives",
  "demostrativo": "demostratiu", "demostrativa": "demostrativa", "demostrativos": "demostratius", "demostrativas": "demostratives",
  "colaborativo": "col·laboratiu", "colaborativa": "col·laborativa", "colaborativos": "col·laboratius", "colaborativas": "col·laboratives",
  "cooperativo": "cooperatiu", "cooperativa": "cooperativa", "cooperativos": "cooperatius", "cooperativas": "cooperatives",
  "productivo": "productiu", "productiva": "productiva", "productivos": "productius", "productivas": "productives",
  "instructivo": "instructiu", "instructiva": "instructiva", "instructivos": "instructius", "instructivas": "instructives",
  "informativo": "informatiu", "informativa": "informativa", "informativos": "informatius", "informativas": "informatives",
  "explicativo": "explicatiu", "explicativa": "explicativa", "explicativos": "explicatius", "explicativas": "explicatives",
  "interactivo": "interactiu", "interactiva": "interactiva", "interactivos": "interactius", "interactivas": "interactives",
  "educativo": "educatiu", "educativa": "educativa", "educativos": "educatius", "educativas": "educatives",
  "reflexivo": "reflexiu", "reflexiva": "reflexiva", "reflexivos": "reflexius", "reflexivas": "reflexives",
  "asertivo": "assertiu", "asertiva": "assertiva", "asertivos": "assertius", "asertivas": "assertives",
  "positivo": "positiu", "positiva": "positiva", "positivos": "positius", "positivas": "positives",
  "negativo": "negatiu", "negativa": "negativa", "negativos": "negatius", "negativas": "negatives",
  "activo": "actiu", "activa": "activa", "activos": "actius", "activas": "actives",
  "pasivo": "passiu", "pasiva": "passiva", "pasivos": "passius", "pasivas": "passives",
  "vivo": "viu", "viva": "viva", "vivos": "vius", "vivas": "vives",
  "propio": "propi", "propia": "pròpia", "propios": "propis", "propias": "pròpies",
  "ajeno": "alié", "ajena": "aliena", "ajenos": "aliens", "ajenas": "alienes",
  "mismo": "mateix", "misma": "mateixa", "mismos": "mateixos", "mismas": "mateixes",
  "otro": "altre", "otra": "altra", "otros": "altres", "otras": "altres",
  "todo": "tot", "toda": "tota", "todos": "tots", "todas": "totes",
  "cada": "cada",
  "mucho": "molt", "mucha": "molta", "muchos": "molts", "muchas": "moltes",
  "poco": "poc", "poca": "poca", "pocos": "pocs", "pocas": "poques",
  "tanto": "tant", "tanta": "tanta", "tantos": "tants", "tantas": "tantes",
  "bastante": "bastant", "bastantes": "bastants",
  "varios": "diversos", "varias": "diverses",
  "distinto": "diferent", "distinta": "diferent", "distintos": "diferents", "distintas": "diferents",
  "diferente": "diferent", "diferentes": "diferents",
  "igual": "igual", "iguales": "iguals",

  // Adverbs, Prepositions, Connectives
  "muy": "molt", "más": "més", "menos": "menys",
  "bien": "bé", "mal": "malament",
  "aquí": "ací", "ahí": "aquí", "allí": "allà",
  "cerca": "prop", "lejos": "lluny",
  "dentro": "dins", "fuera": "fora",
  "arriba": "dalt", "abajo": "baix",
  "delante": "davant", "detrás": "darrere",
  "antes": "abans", "después": "després",
  "pronto": "prompte", "tarde": "tard",
  "temprano": "d'hora",
  "siempre": "sempre", "nunca": "mai", "jamás": "mai",
  "también": "també", "tampoco": "tampoc",
  "ya": "ja", "todavía": "encara", "aún": "encara",
  "solo": "només", "solamente": "únicament",
  "incluso": "fins i tot",
  "casi": "quasi",
  "apenas": "a penes",
  "así": "així",
  "cómo": "com", "como": "com",
  "cuándo": "quan", "cuando": "quan",
  "dónde": "on", "donde": "on",
  "por": "per", "para": "per a",
  "con": "amb", "sin": "sense",
  "sobre": "sobre", "entre": "entre",
  "hacia": "cap a", "hasta": "fins a", "desde": "des de",
  "según": "segons", "durante": "durant", "mediante": "mitjançant",
  "contra": "contra", "ante": "davant de", "tras": "després de",
  "bajo": "sota",
  "pero": "però", "sino": "sinó",
  "porque": "perquè", "por qué": "per què",
  "si": "si", "no": "no",
  "y": "i", "e": "i",
  "o": "o", "u": "o",
  "que": "que", "qué": "què",
  "quien": "qui", "quienes": "qui", "quién": "qui", "quiénes": "qui",
  "cual": "qual", "cuales": "quals", "cuál": "quin", "cuáles": "quins",
  "cuanto": "quant", "cuanta": "quanta", "cuantos": "quants", "cuantas": "quantes",
  "cuánto": "quant", "cuánta": "quanta", "cuántos": "quants", "cuántas": "quantes",
  "este": "aquest", "esta": "aquesta", "estos": "aquests", "estas": "aquestes",
  "ese": "eixe", "esa": "eixa", "esos": "eixos", "esas": "eixes",
  "aquel": "aquell", "aquella": "aquella", "aquellos": "aquells", "aquellas": "aquelles",
  "esto": "això", "eso": "això", "aquello": "allò",
  "mi": "el meu", "mis": "els meus",
  "tu": "el teu", "tus": "els teus",
  "su": "el seu", "sus": "els seus",
  "nuestro": "el nostre", "nuestra": "la nostra", "nuestros": "els nostres", "nuestras": "les nostres",
  "vuestro": "el vostre", "vuestra": "la vostra", "vuestros": "els vostres", "vuestras": "les vostres",
  "me": "em", "te": "et", "se": "es", "nos": "ens", "os": "us",
  "le": "li", "les": "els", "lo": "el", "la": "la", "los": "els", "las": "les"
};
