const fs = require('fs');

// We test our translation dictionary and rules
function translateText(text) {
  if (!text || typeof text !== 'string') return text;
  let t = text;

  // 1. Fixed Educational & Salon Multi-word Phrases
  const phrases = [
    [/Formación Profesional Básica/gi, "Formació Professional Bàsica"],
    [/Formación Profesional/gi, "Formació Professional"],
    [/FP Básica/gi, "FP Bàsica"],
    [/atención al cliente/gi, "atenció al client"],
    [/Atención al cliente/gi, "Atenció al client"],
    [/cuero cabelludo/gi, "cuir cabellut"],
    [/Cuero cabelludo/gi, "Cuir cabellut"],
    [/lavado de cabeza/gi, "rentat de cap"],
    [/lavado y cambios de forma/gi, "rentat i canvis de forma"],
    [/cambios de color del cabello/gi, "canvis de color del cabell"],
    [/cambios de color/gi, "canvis de color"],
    [/cambio de color/gi, "canvi de color"],
    [/cambios de forma/gi, "canvis de forma"],
    [/cambio de forma/gi, "canvi de forma"],
    [/preparación del entorno profesional/gi, "preparació de l'entorn professional"],
    [/cuidados estéticos básicos de uñas/gi, "cures estètiques bàsiques d'ungles"],
    [/ciencias aplicadas/gi, "ciències aplicades"],
    [/Ciencias aplicadas/gi, "Ciències aplicades"],
    [/comunicación y sociedad/gi, "comunicació i societat"],
    [/Comunicación y sociedad/gi, "Comunicació i societat"],
    [/depilación mecánica y decoloración del vello superfluo/gi, "depilació mecànica i decoloració del pèl superflu"],
    [/depilación mecánica/gi, "depilació mecànica"],
    [/decoloración del vello/gi, "decoloració del pèl"],
    [/itinerario personal para la empleabilidad/gi, "itinerari personal per a l'ocupabilitat"],
    [/Itinerario personal para la empleabilidad/gi, "Itinerari personal per a l'ocupabilitat"],
    [/aula-taller/gi, "aula taller"],
    [/aula taller/gi, "aula taller"],
    [/salón de peluquería/gi, "saló de perruqueria"],
    [/salón de belleza/gi, "saló de bellesa"],
    [/salón/gi, "saló"],
    [/en el salón/gi, "al saló"],
    [/del salón/gi, "del saló"],
    [/al salón/gi, "al saló"],
    [/lectura fácil/gi, "lectura fàcil"],
    [/Lectura fácil/gi, "Lectura fàcil"],
    [/apoyos visuales/gi, "suports visuals"],
    [/apoyo visual/gi, "suport visual"],
    [/apoyos pautados/gi, "suports pautats"],
    [/instrucciones visuales/gi, "instruccions visuals"],
    [/Instrucciones visuales/gi, "Instruccions visuals"],
    [/trabajo en parejas/gi, "treball en parelles"],
    [/trabajo en equipo/gi, "treball en equip"],
    [/trabajo colaborativo/gi, "treball col·laboratiu"],
    [/por parejas/gi, "per parelles"],
    [/en parejas/gi, "en parelles"],
    [/en pareja/gi, "en parella"],
    [/por equipos/gi, "per equips"],
    [/en equipo/gi, "en equip"],
    [/evaluación formativa/gi, "avaluació formativa"],
    [/rúbrica visual/gi, "rúbrica visual"],
    [/Rúbrica visual/gi, "Rúbrica visual"],
    [/producto final/gi, "producte final"],
    [/Producto final/gi, "Producte final"],
    [/situaciones reales/gi, "situacions reals"],
    [/situación de aprendizaje/gi, "situació d'aprenentatge"],
    [/situaciones de aprendizaje/gi, "situacions d'aprenentatge"],
    [/medidas DUA/gi, "mesures DUA"],
    [/Medidas DUA/gi, "Mesures DUA"],
    [/modelado previo por el docente/gi, "modelatge previ pel docent"],
    [/modelado previo del docente/gi, "modelatge previ del docent"],
    [/paso a paso/gi, "pas a pas"],
    [/hoja de trabajo/gi, "full de treball"],
    [/ficha de trabajo/gi, "fitxa de treball"],
    [/ficha de cliente/gi, "fitxa de client"],
    [/ficha técnica/gi, "fitxa tècnica"],
    [/lista de cotejo/gi, "llista de control"],
    [/banco de operaciones/gi, "banc d'operacions"],
    [/banco de palabras/gi, "banc de paraules"],
    [/lluvia de ideas/gi, "pluja d'idees"],
    [/juego de rol/gi, "joc de rol"],
    [/mapa conceptual/gi, "mapa conceptual"],
    [/marca personal/gi, "marca personal"],
    [/cliente misterioso/gi, "client misteriós"],
    [/redes sociales/gi, "xarxes socials"],
    [/imagen personal y profesional/gi, "imatge personal i professional"],
    [/imagen personal/gi, "imatge personal"],
    [/imagen profesional/gi, "imatge professional"],
    [/prevención de riesgos laborales/gi, "prevenció de riscos laborals"],
    [/Prevención de riesgos laborales/gi, "Prevenció de riscos laborals"],
    [/deontología profesional/gi, "deontologia professional"],
    [/higiene y seguridad/gi, "higiene i seguretat"],
    [/seguridad e higiene/gi, "seguretat i higiene"],
    [/salud y seguridad/gi, "salut i seguretat"],
    [/medio ambiente/gi, "medi ambient"],
    [/medioambiental/gi, "mediambiental"],
    [/medioambientales/gi, "mediambientals"],
    [/tiempo de exposición/gi, "temps d'exposició"],
    [/tiempos de exposición/gi, "temps d'exposició"],
    [/secador de mano/gi, "assecador de mà"],
    [/secador de casco/gi, "assecador de casc"],
    [/lavacabezas/gi, "rentacaps"],
    [/cepillo redondo/gi, "raspall redó"],
    [/cepillo de pelo/gi, "raspall de cabell"],
    [/peine de púas/gi, "pinta de pues"],
    [/peine/gi, "pinta"],
    [/cepillo/gi, "raspall"],
    [/esmaltado de uñas/gi, "esmaltat d'ungles"],
    [/esmalte de uñas/gi, "esmalt d'ungles"],
    [/quitaesmalte/gi, "dissolvent d'esmalt"],
    [/corte de pelo/gi, "tall de cabell"],
    [/corte y peinado/gi, "tall i pentinat"],
    [/cambio de look/gi, "canvi de look"],
    [/toma de decisiones/gi, "presa de decisions"],
    [/resolución de conflictos/gi, "resolució de conflictes"],
    [/búsqueda de empleo/gi, "cerca d'ocupació"],
    [/mercado laboral/gi, "mercat laboral"],
    [/inserción laboral/gi, "inserció laboral"],
    [/entorno de trabajo/gi, "entorn de treball"],
    [/puesto de trabajo/gi, "lloc de treball"],
    [/centro de trabajo/gi, "centre de treball"],
    [/mundo laboral/gi, "món laboral"],
    [/vida cotidiana/gi, "vida quotidiana"],
    [/vida real/gi, "vida real"]
  ];

  for (const [re, rep] of phrases) {
    t = t.replace(re, rep);
  }

  return t;
}

const sample = "el alumnado crea una guía visual que podría estar en el vestuario o entrada del aula-taller. Objetivo: identificar la imagen personal adecuada para trabajar en peluquería y estética: higiene, uniforme, calzado, cabello, manos, uñas, postura y actitud. Desarrollo: | formato carrusel de Instagram o póster tipo “Get ready with me profesional”, pero sin frivolizar la seguridad. Producto final: manual visual de imagen profesional. Evaluación: claridad, rigor, presentación, lenguaje inclusivo, relación con seguridad e higiene.";
console.log("Output test:", translateText(sample));
