const fs = require('fs');

const MODULE_NAMES_CA = {
  "3060": "Preparació de l’entorn professional",
  "3061": "Cures estètiques bàsiques d’ungles",
  "3005": "Atenció al client",
  "3065": "Canvis de color del cabell",
  "3042": "Ciències aplicades II",
  "3009": "Ciències aplicades I",
  "3011": "Comunicació i societat I",
  "3012": "Comunicació i societat II",
  "3062": "Depilació mecànica i decoloració del pèl superflu",
  "3159": "Itinerari personal per a l’ocupabilitat",
  "3064": "Rentat i canvis de forma del cabell",
  "3063": "Maquillatge",
  "3067": "Formació en Centres de Treball (FCT)"
};

// Comprehensive dictionary for vocational education in hair, beauty, science and communication
const PHRASE_REPLACEMENTS = [
  // Curricular connection titles
  [/Conexión curricular:\s*([0-9a-zA-Z\-]+)\s*↔\s*([0-9a-zA-Z\-]+)\s*\(([^)]+)\)/g, (match, p1, p2, p3) => {
    let modNameCa = p3;
    for (const [code, nameCa] of Object.entries(MODULE_NAMES_CA)) {
      if (p3.toLowerCase().includes(nameCa.toLowerCase().substring(0, 8))) {
        modNameCa = nameCa;
        break;
      }
    }
    return `Connexió curricular: ${p1} ↔ ${p2} (${modNameCa})`;
  }],
  [/Conexión competencial y curricular entre los criterios de evaluación de ([^y]+) y el resto de módulos del ciclo formativo para garantizar una formación integral\./gi, 
   (match, p1) => {
     let modNameCa = p1.trim();
     for (const [code, nameCa] of Object.entries(MODULE_NAMES_CA)) {
       if (p1.toLowerCase().includes(code) || p1.toLowerCase().includes(nameCa.toLowerCase().substring(0, 8))) {
         modNameCa = nameCa;
         break;
       }
     }
     return `Connexió competencial i curricular entre els criteris d'avaluació de ${modNameCa} i la resta de mòduls del cicle formatiu per a garantir una formació integral.`;
   }
  ],

  // Common titles
  [/Imagen personal y profesional: “cómo me presento también forma parte del servicio”/gi, "Imatge personal i professional: “com em presente també forma part del servei”"],
  [/Recepción, agenda, ficha de cliente y primera atención/gi, "Recepció, agenda, fitxa de client i primera atenció"],
  [/TIC, documentación, comunicación escrita y portfolio profesional/gi, "TIC, documentació, comunicació escrita i portafoli professional"],
  [/Trabajo en equipo, roles, convivencia y simulación de salón/gi, "Treball en equip, rols, convivència i simulació de saló"],
  [/Preparación para FCT, empleabilidad y emprendimiento/gi, "Preparació per a la FCT, ocupabilitat i emprenedoria"],
  [/Preparación, limpieza, desinfección y esterilización de instalaciones/gi, "Preparació, neteja, desinfecció i esterilització d'instal·lacions"],
  [/Recepción, almacenamiento, conservación y control de materiales y productos/gi, "Recepció, emmagatzematge, conservació i control de materials i productes"],
  [/Acomodación, ergonomía y protección del cliente/gi, "Acomodació, ergonomia i protecció del client"],
  [/Seguridad, PRL, EPI y actuación ante incidencias/gi, "Seguretat, PRL, EPI i actuació davant incidències"],
  [/Sostenibilidad, residuos y consumo responsable/gi, "Sostenibilitat, residus i consum responsable"],
  [/Imagen profesional, preparación personal, actitud y deontología/gi, "Imatge professional, preparació personal, actitud i deontologia"],
  [/Preparación de equipos, útiles, productos y mesa de trabajo/gi, "Preparació d'equips, estris, productes i taula de treball"],
  [/Observación de uñas, piel, alteraciones, contraindicaciones y derivación/gi, "Observació d'ungles, pell, alteracions, contraindicacions i derivació"],
  [/Diseño, nail art, creatividad, color, armonía estética e imagen global/gi, "Disseny, nail art, creativitat, color, harmonia estètica i imatge global"],
  [/Ergonomía, acomodación, protección y confort del cliente y del profesional/gi, "Ergonomia, acomodació, protecció i confort del client i del professional"],
  [/Comunicación, atención al cliente, satisfacción, cuidados posteriores y reclamaciones/gi, "Comunicació, atenció al client, satisfacció, cures posteriors i reclamacions"],
  [/Documentación profesional, fichas técnicas, TIC, portfolio y confidencialidad/gi, "Documentació professional, fitxes tècniques, TIC, portafoli i confidencialitat"],
  [/Control de tiempos, calidad, eficiencia y mejora del servicio/gi, "Control de temps, qualitat, eficiència i millora del servei"],
  [/Limpieza final, conservación, residuos, sostenibilidad y consumo responsable/gi, "Neteja final, conservació, residus, sostenibilitat i consum responsable"],
  [/Trabajo en equipo, autonomía, responsabilidad y aplicación en FCT/gi, "Treball en equip, autonomia, responsabilitat i aplicació en FCT"],
  [/Higiene, desinfección, esterilización y prevención de infecciones/gi, "Higiene, desinfecció, esterilització i prevenció d'infeccions"],
  [/Selección de cosméticos, esmaltes, útiles y técnicas según características del cliente/gi, "Selecció de cosmètics, esmalts, estris i tècniques segons característiques del client"],
  [/Ejecución técnica de pedicura: higiene, durezas superficiales, limado, cutículas, masaje y esmaltado/gi, "Execució tècnica de pedicura: higiene, dureses superficials, llimat, cutícules, massatge i esmaltat"],
  [/Ejecución técnica de manicura: fases, destreza manual, limado, cutículas, pulido, masaje y esmaltado/gi, "Execució tècnica de manicura: fases, destresa manual, llimat, cutícules, polit, massatge i esmaltat"],

  // Fixed Activity & DUA formula phrases
  [/Reto práctico motivador conectado con situaciones reales del salón y ([^.]+)/gi, "Repte pràctic motivador connectat amb situacions reals del saló i $1"],
  [/Reto práctico aplicable directamente a la profesión y entorno real de ([^.]+)/gi, "Repte pràctic aplicable directament a la professió i entorn real de $1"],
  [/Ficha de trabajo, rúbrica de ejecución y producto demostrativo de ([^.]+)/gi, "Fitxa de treball, rúbrica d'execució i producte demostratiu de $1"],
  [/Rúbrica visual y producto de evaluación formativa\./gi, "Rúbrica visual i producte d'avaluació formativa."],
  [/Rúbrica visual y producto de evaluación formativa/gi, "Rúbrica visual i producte d'avaluació formativa"],
  [/vídeo interno o demostración en clase con rúbrica de acogida\./gi, "Vídeo intern o demostració a classe amb rúbrica d'acollida."],
  [/Medidas DUA con apoyos visuales y lectura fácil\./gi, "Mesures DUA amb suports visuals i lectura fàcil."],
  [/Medidas DUA con lectura fácil y apoyos visuales\./gi, "Mesures DUA amb lectura fàcil i suports visuals."],
  [/Instrucciones visuales, apoyos pautados y trabajo en parejas\./gi, "Instruccions visuals, suports pautats i treball en parelles."],
  [/Instrucciones visuales, apoyos pautados y trabajo en parejas/gi, "Instruccions visuals, suports pautats i treball en parelles"],
  [/Instrucciones visuales paso a paso, modelado previo por el docente, lectura fácil y trabajo en parejas\./gi, "Instruccions visuals pas a pas, modelatge previ pel docent, lectura fàcil i treball en parelles."],
  [/Instrucciones visuales paso a paso, modelado previo del docente, roles cooperativos y lectura fácil\./gi, "Instruccions visuals pas a pas, modelatge previ del docent, rols cooperatius i lectura fàcil."],
  [/Problemas graduados por dificultad, banco de operaciones, apoyo visual y exposición opcional en pareja\./gi, "Problemes graduats per dificultat, banc d'operacions, suport visual i exposició opcional en parella."],
  [/Fuentes seleccionadas, lectura fácil, imágenes, roles, plantilla de cartel y exposición breve en pareja\./gi, "Fonts seleccionades, lectura fàcil, imatges, rols, plantilla de cartell i exposició breu en parella."],

  // Section labels inside text
  [/Contexto \/ idea motivadora:/gi, "Context / idea motivadora:"],
  [/Contexto \/ Idea motivadora:/gi, "Context / Idea motivadora:"],
  [/Producto \/ evidencia:/gi, "Producte / evidència:"],
  [/Producto \/ Evidencia:/gi, "Producte / Evidència:"],
  [/Producto final:/gi, "Producte final:"],
  [/Objetivo:/gi, "Objectiu:"],
  [/Desarrollo:/gi, "Desenvolupament:"],
  [/Evaluación:/gi, "Avaluació:"],
  [/Aprendizajes y criterios evaluables:/gi, "Aprenentatges i criteris avaluables:"],
  [/Aprendizajes y Diversidad FPB:/gi, "Aprenentatges i Diversitat FPB:"],
  [/Ayudas \/ pautas DUA:/gi, "Ajudes / pautes DUA:"],

  // Core Vocabulary Phrases
  [/\bel alumnado\b/gi, "l'alumnat"],
  [/\balumnado\b/gi, "alumnat"],
  [/\baula-taller\b/gi, "aula taller"],
  [/\baula taller\b/gi, "aula taller"],
  [/\ben el aula taller\b/gi, "a l'aula taller"],
  [/\ben el aula-taller\b/gi, "a l'aula taller"],
  [/\bdel aula taller\b/gi, "de l'aula taller"],
  [/\bdel aula-taller\b/gi, "de l'aula taller"],
  [/\bsalón de peluquería\b/gi, "saló de perruqueria"],
  [/\bsalón de belleza\b/gi, "saló de bellesa"],
  [/\ben el salón\b/gi, "al saló"],
  [/\bdel salón\b/gi, "del saló"],
  [/\bal salón\b/gi, "al saló"],
  [/\bsalón\b/gi, "saló"],
  [/\bsalones\b/gi, "salons"],
  [/\bcuero cabelludo\b/gi, "cuir cabellut"],
  [/\bcabello\b/gi, "cabell"],
  [/\bcabellos\b/gi, "cabells"],
  [/\bcuidados estéticos\b/gi, "cures estètiques"],
  [/\buñas\b/gi, "ungles"],
  [/\buña\b/gi, "ungla"],
  [/\blavacabezas\b/gi, "rentacaps"],
  [/\bchampú\b/gi, "xampú"],
  [/\bchampús\b/gi, "xampús"],
  [/\bacondicionador\b/gi, "condicionador"],
  [/\bacondicionadores\b/gi, "condicionadors"],
  [/\bsecador de mano\b/gi, "assecador de mà"],
  [/\bsecador de casco\b/gi, "assecador de casc"],
  [/\bsecador\b/gi, "assecador"],
  [/\bsecadores\b/gi, "assecadors"],
  [/\bcepillo redondo\b/gi, "raspall redó"],
  [/\bcepillo\b/gi, "raspall"],
  [/\bcepillos\b/gi, "raspalls"],
  [/\bpeine de púas\b/gi, "pinta de pues"],
  [/\bpeine\b/gi, "pinta"],
  [/\bpeines\b/gi, "pintes"],
  [/\btijeras\b/gi, "tisores"],
  [/\btijera\b/gi, "tisora"],
  [/\btoalla\b/gi, "tovallola"],
  [/\btoallas\b/gi, "tovalloles"],
  [/\bbata de protección\b/gi, "bata de protecció"],
  [/\bcapa de corte\b/gi, "capa de tall"],
  [/\bguantes\b/gi, "guants"],
  [/\bmascarilla\b/gi, "mascareta"],
  [/\bmascarillas\b/gi, "mascaretes"],
  [/\bdepilación mecánica\b/gi, "depilació mecànica"],
  [/\bdepilación\b/gi, "depilació"],
  [/\bdecoloración del vello\b/gi, "decoloració del pèl"],
  [/\bdecoloración\b/gi, "decoloració"],
  [/\bvello superfluo\b/gi, "pèl superflu"],
  [/\bvello\b/gi, "pèl"],
  [/\bpestañas\b/gi, "pestanyes"],
  [/\bpestaña\b/gi, "pestanya"],
  [/\bcejas\b/gi, "celles"],
  [/\bceja\b/gi, "cella"],
  [/\bmejillas\b/gi, "galtes"],
  [/\bmejilla\b/gi, "galta"],
  [/\blabios\b/gi, "llavis"],
  [/\blabio\b/gi, "llavi"],
  [/\bojos\b/gi, "ulls"],
  [/\bojo\b/gi, "ull"],
  [/\bpiel\b/gi, "pell"],
  [/\brostro\b/gi, "rostre"],
  [/\bcuello\b/gi, "coll"],
  [/\bescote\b/gi, "escot"],
  [/\bmanos\b/gi, "mans"],
  [/\bmano\b/gi, "mà"],
  [/\bpies\b/gi, "peus"],
  [/\bpie\b/gi, "peu"],
  [/\bdurezas\b/gi, "dureses"],
  [/\bcutículas\b/gi, "cutícules"],
  [/\bcutícula\b/gi, "cutícula"],
  [/\besmaltado\b/gi, "esmaltat"],
  [/\besmalte de uñas\b/gi, "esmalt d'ungles"],
  [/\besmalte\b/gi, "esmalt"],
  [/\besmalts\b/gi, "esmalts"],
  [/\bmaquillaje social\b/gi, "maquillatge social"],
  [/\bmaquillaje de fantasía\b/gi, "maquillatge de fantasia"],
  [/\bmaquillaje\b/gi, "maquillatge"],
  [/\bmaquillajes\b/gi, "maquillatges"],
  [/\bvisagismo\b/gi, "visatgisme"],
  [/\bmanicura\b/gi, "manicura"],
  [/\bpedicura\b/gi, "pedicura"],
  [/\bfijador\b/gi, "fixador"],
  [/\bfijadores\b/gi, "fixadors"],
  [/\btinte\b/gi, "tint"],
  [/\btintes\b/gi, "tints"],
  [/\bmechas\b/gi, "metxes"],
  [/\bmecha\b/gi, "metxa"],
  [/\bpeinado\b/gi, "pentinat"],
  [/\bpeinados\b/gi, "pentinats"],
  [/\bmarcado\b/gi, "marcat"],
  [/\bmarcados\b/gi, "marcats"],
  [/\bmolde\b/gi, "motle"],
  [/\bmoldes\b/gi, "motles"],
  [/\bhorquilla\b/gi, "forqueta"],
  [/\bhorquillas\b/gi, "forquetes"],
  [/\bpasador\b/gi, "passador"],
  [/\bpasadores\b/gi, "passadors"],
  [/\balbarán\b/gi, "albarà"],
  [/\balbaranes\b/gi, "albarans"],
  [/\bstock\b/gi, "estoc"],
  [/\balmacén\b/gi, "magatzem"],
  [/\balmacenes\b/gi, "magatzems"],
  [/\bexistencias\b/gi, "existències"],
  [/\bmercancías\b/gi, "mercaderies"],
  [/\bmercancía\b/gi, "mercaderia"],
  [/\bcaducidad\b/gi, "caducitat"],
  [/\bdesechos\b/gi, "residus"],
  [/\bresiduos\b/gi, "residus"],
  [/\bun solo uso\b/gi, "un sol ús"],
  [/\bde un solo uso\b/gi, "d'un sol ús"],
  [/\bdesechable\b/gi, "d'un sol ús"],
  [/\bdesechables\b/gi, "d'un sol ús"],
  [/\blectura fácil\b/gi, "lectura fàcil"],
  [/\bapoyos visuales\b/gi, "suports visuals"],
  [/\bapoyo visual\b/gi, "suport visual"],
  [/\bapoyos pautados\b/gi, "suports pautats"],
  [/\binstrucciones visuales\b/gi, "instruccions visuals"],
  [/\btrabajo en parejas\b/gi, "treball en parelles"],
  [/\btrabajo en equipo\b/gi, "treball en equip"],
  [/\btrabajo colaborativo\b/gi, "treball col·laboratiu"],
  [/\bpor parejas\b/gi, "per parelles"],
  [/\ben parejas\b/gi, "en parelles"],
  [/\ben pareja\b/gi, "en parella"],
  [/\bpor equipos\b/gi, "per equips"],
  [/\ben equipo\b/gi, "en equip"],
  [/\broles cooperativos\b/gi, "rols cooperatius"],
  [/\bassignación de roles\b/gi, "assignació de rols"],
  [/\bevaluación formativa\b/gi, "avaluació formativa"],
  [/\brúbrica visual\b/gi, "rúbrica visual"],
  [/\bproducto final\b/gi, "producte final"],
  [/\bsituaciones reales\b/gi, "situacions reals"],
  [/\bsituación de aprendizaje\b/gi, "situació d'aprenentatge"],
  [/\bsituaciones de aprendizaje\b/gi, "situacions d'aprenentatge"],
  [/\bmodelado previo por el docente\b/gi, "modelatge previ pel docent"],
  [/\bmodelado previo del docente\b/gi, "modelatge previ del docent"],
  [/\bmodelado previo\b/gi, "modelatge previ"],
  [/\bpaso a paso\b/gi, "pas a pas"],
  [/\bhoja de trabajo\b/gi, "full de treball"],
  [/\bficha de trabajo\b/gi, "fitxa de treball"],
  [/\bficha de cliente\b/gi, "fitxa de client"],
  [/\bficha técnica\b/gi, "fitxa tècnica"],
  [/\blista de cotejo\b/gi, "llista de control"],
  [/\bbanco de operaciones\b/gi, "banc d'operacions"],
  [/\bbanco de palabras\b/gi, "banc de paraules"],
  [/\blluvia de ideas\b/gi, "pluja d'idees"],
  [/\bjuego de rol\b/gi, "joc de rol"],
  [/\bjuego de roles\b/gi, "joc de rols"],
  [/\bmapa conceptual\b/gi, "mapa conceptual"],
  [/\bmarca personal\b/gi, "marca personal"],
  [/\bcliente misterioso\b/gi, "client misteriós"],
  [/\bredes sociales\b/gi, "xarxes socials"],
  [/\bimagen personal y profesional\b/gi, "imatge personal i professional"],
  [/\bimagen personal\b/gi, "imatge personal"],
  [/\bimagen profesional\b/gi, "imatge professional"],
  [/\bprevención de riesgos laborales\b/gi, "prevenció de riscos laborals"],
  [/\bdeontología profesional\b/gi, "deontologia professional"],
  [/\bhigiene y seguridad\b/gi, "higiene i seguretat"],
  [/\bseguridad e higiene\b/gi, "seguretat i higiene"],
  [/\bsalud y seguridad\b/gi, "salut i seguretat"],
  [/\bmedio ambiente\b/gi, "medi ambient"],
  [/\bmedioambiental\b/gi, "mediambiental"],
  [/\bmedioambientales\b/gi, "mediambientals"],
  [/\btiempo de exposición\b/gi, "temps d'exposició"],
  [/\btiempos de exposición\b/gi, "temps d'exposició"],
  [/\btiempos\b/gi, "temps"],
  [/\btiempo\b/gi, "temps"],
  [/\bde forma adecuada\b/gi, "de manera adequada"],
  [/\bde forma\b/gi, "de manera"],
  [/\bde modo\b/gi, "de manera"],
  [/\ba través de\b/gi, "a través de"],
  [/\ben función de\b/gi, "en funció de"],
  [/\bteniendo en cuenta\b/gi, "tenint en compte"],
  [/\bantes de entrar\b/gi, "abans d'entrar"],
  [/\bantes de\b/gi, "abans de"],
  [/\bdespués de\b/gi, "després de"],
  [/\ben caso de\b/gi, "en cas de"],
  [/\ben caso afirmativo\b/gi, "en cas afirmatiu"],
  [/\ben caso contrario\b/gi, "en cas contrari"],
  [/\ba contrapelo\b/gi, "a contrapèl"],
  [/\bpor cuenta ajena\b/gi, "per compte d'altri"],
  [/\bpor cuenta propia\b/gi, "per compte propi"],
  [/\ba corto plazo\b/gi, "a curt termini"],
  [/\ba largo plazo\b/gi, "a llarg termini"],
  [/\ba medio plazo\b/gi, "a mitjà termini"]
];

// Single word replacements (with case preservation)
const WORD_MAP = {
  // Grammar words
  "el": "el",
  "la": "la",
  "los": "els",
  "las": "les",
  "un": "un",
  "una": "una",
  "unos": "uns",
  "unas": "unes",
  "y": "i",
  "e": "i",
  "o": "o",
  "u": "o",
  "pero": "però",
  "sino": "sinó",
  "porque": "perquè",
  "por": "per",
  "para": "per a",
  "con": "amb",
  "sin": "sense",
  "sobre": "sobre",
  "entre": "entre",
  "hacia": "cap a",
  "hasta": "fins a",
  "desde": "des de",
  "según": "segons",
  "durante": "durant",
  "mediante": "mitjançant",
  "tras": "després de",
  "donde": "on",
  "cuando": "quan",
  "como": "com",
  "muy": "molt",
  "más": "més",
  "menos": "menys",
  "mucho": "molt",
  "mucha": "molta",
  "muchos": "molts",
  "muchas": "moltes",
  "poco": "poc",
  "poca": "poca",
  "pocos": "pocs",
  "pocas": "poques",
  "todo": "tot",
  "toda": "tota",
  "todos": "tots",
  "todas": "totes",
  "cada": "cada",
  "otro": "altre",
  "otra": "altra",
  "otros": "altres",
  "otras": "altres",
  "mismo": "mateix",
  "misma": "mateixa",
  "mismos": "mateixos",
  "mismas": "mateixes",
  "también": "també",
  "tampoco": "tampoc",
  "siempre": "sempre",
  "nunca": "mai",
  "ya": "ja",
  "aún": "encara",
  "todavía": "encara",
  "bien": "bé",
  "mal": "malament",
  "así": "així",
  "este": "aquest",
  "esta": "aquesta",
  "estos": "aquests",
  "estas": "aquestes",
  "esto": "açò",
  "ese": "eixe",
  "esa": "eixa",
  "esos": "eixos",
  "esas": "eixes",
  "eso": "això",
  "aquel": "aquell",
  "aquella": "aquella",
  "aquellos": "aquells",
  "aquellas": "aquelles",
  "su": "el seu",
  "sus": "els seus",

  // Educational & Professional Domain Nouns
  "alumnado": "alumnat",
  "alumno": "alumne",
  "alumna": "alumna",
  "alumnos": "alumnes",
  "alumnas": "alumnes",
  "docente": "docent",
  "docentes": "docents",
  "profesor": "professor",
  "profesora": "professora",
  "equipo": "equip",
  "equipos": "equips",
  "grupo": "grup",
  "grupos": "grups",
  "pareja": "parella",
  "parejas": "parelles",
  "reto": "repte",
  "retos": "reptes",
  "tarea": "tasca",
  "tareas": "tasques",
  "actividad": "activitat",
  "actividades": "activitats",
  "proyecto": "projecte",
  "proyectos": "projectes",
  "evaluación": "avaluació",
  "evaluaciones": "avaluacions",
  "rúbrica": "rúbrica",
  "rúbricas": "rúbriques",
  "evidencia": "evidència",
  "evidencias": "evidències",
  "criterio": "criteri",
  "criterios": "criteris",
  "objetivo": "objectiu",
  "objetivos": "objectius",
  "desarrollo": "desenvolupament",
  "producto": "producte",
  "productos": "productes",
  "plantilla": "plantilla",
  "plantillas": "plantilles",
  "ficha": "fitxa",
  "fichas": "fitxes",
  "guía": "guia",
  "guías": "guies",
  "guion": "guió",
  "guiones": "guions",
  "cartel": "cartell",
  "carteles": "cartells",
  "póster": "pòster",
  "pósters": "pòsters",
  "mural": "mural",
  "murales": "murals",
  "vídeo": "vídeo",
  "vídeos": "vídeos",
  "tarjeta": "targeta",
  "tarjetas": "targetes",
  "banco": "banc",
  "bancos": "bancs",
  "tabla": "taula",
  "tablas": "taules",
  "gráfico": "gràfic",
  "gráfica": "gràfica",
  "gráficos": "gràfics",
  "gráficas": "gràfiques",
  "datos": "dades",
  "dato": "dada",
  "ejemplo": "exemple",
  "ejemplos": "exemples",
  "caso": "cas",
  "casos": "casos",
  "situación": "situació",
  "situaciones": "situacions",
  "pregunta": "pregunta",
  "preguntas": "preguntes",
  "respuesta": "resposta",
  "respuestas": "respostes",
  "duda": "dubte",
  "dudas": "dubtes",
  "queja": "queixa",
  "quejas": "queixes",
  "reclamación": "reclamació",
  "reclamaciones": "reclamacions",
  "cliente": "client",
  "clientes": "clients",
  "usuario": "usuari",
  "usuarios": "usuaris",
  "persona": "persona",
  "personas": "persones",
  "servicio": "servei",
  "servicios": "serveis",
  "atención": "atenció",
  "recepción": "recepció",
  "cita": "cita",
  "citas": "cites",
  "agenda": "agenda",
  "horario": "horari",
  "horarios": "horaris",
  "saludo": "salutació",
  "saludos": "salutacions",
  "despedida": "comiat",
  "despedidas": "comiats",
  "trato": "tracte",
  "acogida": "acollida",
  "empresa": "empresa",
  "empresas": "empreses",
  "taller": "taller",
  "talleres": "tallers",
  "aula": "aula",
  "aulas": "aules",
  "entorno": "entorn",
  "entornos": "entorns",
  "puesto": "lloc",
  "puestos": "llocs",
  "espacio": "espai",
  "espacios": "espais",
  "zona": "zona",
  "zonas": "zones",
  "vestuario": "vestidor",
  "vestuarios": "vestidors",
  "uniforme": "uniforme",
  "uniformes": "uniformes",
  "calzado": "calçat",
  "ropa": "roba",
  "higiene": "higiene",
  "limpieza": "neteja",
  "desinfección": "desinfecció",
  "esterilización": "esterilització",
  "seguridad": "seguretat",
  "salud": "salut",
  "enfermedad": "malaltia",
  "enfermedades": "malalties",
  "riesgo": "risc",
  "riesgos": "riscos",
  "protección": "protecció",
  "prevención": "prevenció",
  "postura": "postura",
  "posturas": "postures",
  "actitud": "actitud",
  "actitudes": "actituds",
  "comportamiento": "comportament",
  "norma": "norma",
  "normas": "normes",
  "protocolo": "protocol",
  "protocolos": "protocols",
  "calidad": "qualitat",
  "mejora": "millora",
  "éxito": "èxit",
  "error": "error",
  "errores": "errors",
  "fallo": "fallada",
  "fallos": "fallades",
  "acabado": "acabat",
  "acabados": "acabats",
  "resultado": "resultat",
  "resultados": "resultats",
  "tiempo": "temps",
  "tiempos": "temps",
  "duración": "duració",
  "proceso": "procés",
  "procesos": "processos",
  "fase": "fase",
  "fases": "fases",
  "paso": "pas",
  "pasos": "passos",
  "método": "mètode",
  "métodos": "mètodes",
  "técnica": "tècnica",
  "técnicas": "tècniques",
  "herramienta": "eina",
  "herramientas": "eines",
  "útil": "estri",
  "útiles": "estris",
  "utensilio": "estri",
  "utensilios": "estris",
  "aparato": "aparell",
  "aparatos": "aparells",
  "equipo": "equip",
  "equipos": "equips",
  "accesorio": "accessori",
  "accesorios": "accessoris",
  "material": "material",
  "materiales": "materials",
  "producto": "producte",
  "productos": "productes",
  "cosmético": "cosmètic",
  "cosméticos": "cosmètics",
  "mezcla": "mescla",
  "mezclas": "mescles",
  "fórmula": "fórmula",
  "fórmulas": "fórmules",
  "cantidad": "quantitat",
  "cantidades": "quantitats",
  "proporción": "proporció",
  "proporciones": "proporcions",
  "medida": "mesura",
  "medidas": "mesures",
  "magnitud": "magnitud",
  "magnitudes": "magnituds",
  "unidad": "unitat",
  "unidades": "unitats",
  "temperatura": "temperatura",
  "calor": "calor",
  "agua": "aigua",
  "aire": "aire",
  "residuos": "residus",
  "residuo": "residu",
  "basura": "fem",
  "reciclaje": "reciclatge",
  "sostenibilidad": "sostenibilitat",
  "consumo": "consum",
  "ahorro": "estalvi",
  "energía": "energia",
  "electricidad": "electricitat",
  "potencia": "potència",
  "voltaje": "voltatge",
  "enchufe": "endoll",
  "enchufes": "endolls",
  "cable": "cable",
  "cables": "cables",
  "química": "química",
  "física": "física",
  "biología": "biologia",
  "matemáticas": "matemàtiques",
  "lengua": "llengua",
  "literatura": "literatura",
  "inglés": "anglés",
  "castellano": "castellà",
  "valenciano": "valencià",
  "catalán": "català",
  "comunicación": "comunicació",
  "sociedad": "societat",
  "historia": "història",
  "geografía": "geografia",
  "paisaje": "paisatge",
  "paisajes": "paisatges",
  "cultura": "cultura",
  "culturas": "cultures",
  "empleo": "ocupació",
  "empleabilidad": "ocupabilitat",
  "itinerario": "itinerari",
  "itinerarios": "itineraris",
  "carrera": "carrera",
  "futuro": "futur",
  "vocación": "vocació",
  "interés": "interés",
  "intereses": "interessos",
  "habilidad": "habilitat",
  "habilidades": "habilitats",
  "destreza": "destresa",
  "destrezas": "destreses",
  "competencia": "competència",
  "competencias": "competències",
  "autoestima": "autoestima",
  "autoconocimiento": "autoconeixement",
  "autonomía": "autonomia",
  "responsabilidad": "responsabilitat",
  "iniciativa": "iniciativa",
  "creatividad": "creativitat",
  "empatía": "empatia",
  "asertividad": "assertivitat",
  "respeto": "respecte",
  "cortesía": "cortesia",
  "discreción": "discreció",
  "confidencialidad": "confidencialitat",
  "deontología": "deontologia",
  "ética": "ètica",
  "derecho": "dret",
  "derechos": "drets",
  "deber": "deure",
  "deberes": "deures",
  "garantía": "garantia",
  "garantías": "garanties",
  "precio": "preu",
  "precios": "preus",
  "coste": "cost",
  "costes": "costos",
  "presupuesto": "pressupost",
  "presupuestos": "pressupostos",
  "descuento": "descompte",
  "descuentos": "descomptes",
  "beneficio": "benefici",
  "beneficios": "beneficis",
  "promoción": "promoció",
  "promociones": "promocions",
  "venta": "venda",
  "ventas": "vendes",
  "compra": "compra",
  "compras": "compres",
  "pago": "pagament",
  "pagos": "pagaments",
  "cobro": "cobrament",
  "cobros": "cobraments",
  "dinero": "diners",
  "factura": "factura",
  "facturas": "factures",
  "recibo": "rebut",
  "recibos": "rebuts",

  // Hair & Beauty Specific Nouns
  "cabello": "cabell",
  "cabellos": "cabells",
  "pelo": "pèl",
  "pelos": "pèls",
  "piel": "pell",
  "pieles": "pells",
  "uña": "ungla",
  "uñas": "ungles",
  "mano": "mà",
  "manos": "mans",
  "pie": "peu",
  "pies": "peus",
  "ceja": "cella",
  "cejas": "celles",
  "pestaña": "pestanya",
  "pestañas": "pestanyes",
  "ojo": "ull",
  "ojos": "ulls",
  "labio": "llavi",
  "labios": "llavis",
  "mejilla": "galta",
  "mejillas": "galtes",
  "cuello": "coll",
  "cuellos": "colls",
  "rostro": "rostre",
  "rostros": "rostres",
  "cara": "cara",
  "caras": "cares",
  "melena": "melena",
  "melenas": "melenes",
  "raíz": "arrel",
  "raíces": "arrels",
  "punta": "punta",
  "puntas": "puntes",
  "tallo": "tija",
  "tallos": "tiges",
  "folículo": "fol·licle",
  "folículos": "fol·licles",
  "cutícula": "cutícula",
  "cutículas": "cutícules",
  "dureza": "duresa",
  "durezas": "dureses",
  "cera": "cera",
  "ceras": "ceres",
  "espátula": "espàtula",
  "espátulas": "espàtules",
  "banda": "banda",
  "bandas": "bandes",
  "papel": "paper",
  "papeles": "papers",
  "algodón": "cotó",
  "algodones": "cotons",
  "pinza": "pinca",
  "pinzas": "pinces",
  "lima": "llima",
  "limas": "llimes",
  "limado": "llimat",
  "pulido": "polit",
  "esmalte": "esmalt",
  "esmaltes": "esmalts",
  "esmaltado": "esmaltat",
  "base": "base",
  "bases": "bases",
  "brillo": "brillantor",
  "brillos": "brillantors",
  "tinte": "tint",
  "tintes": "tints",
  "tinta": "tinta",
  "coloración": "coloració",
  "coloraciones": "coloracions",
  "decoloración": "decoloració",
  "decoloraciones": "decoloracions",
  "mecha": "metxa",
  "mechas": "metxes",
  "reflejo": "reflex",
  "reflejos": "reflexos",
  "tono": "to",
  "tonos": "tos",
  "matiz": "matís",
  "matices": "matisos",
  "peinado": "pentinat",
  "peinados": "pentinats",
  "corte": "tall",
  "cortes": "talls",
  "recogido": "recollit",
  "recogidos": "recollits",
  "marcado": "marcat",
  "marcados": "marcats",
  "molde": "motle",
  "moldes": "motles",
  "rulo": "rulo",
  "rulos": "rulos",
  "secado": "assecatge",
  "lavado": "rentat",
  "lavados": "rentats",
  "aclarado": "esbandit",
  "masaje": "massatge",
  "masajes": "massatges",
  "manicura": "manicura",
  "manicuras": "manicures",
  "pedicura": "pedicura",
  "pedicuras": "pedicures",
  "maquillaje": "maquillatge",
  "maquillajes": "maquillatges",
  "sombra": "ombra",
  "sombras": "ombres",
  "colorete": "coloret",
  "coloretes": "colorets",
  "labial": "barra de llavis",
  "labiales": "barres de llavis",
  "pincel": "pinzell",
  "pinceles": "pinzells",
  "brocha": "brotxa",
  "brochas": "brotxes",
  "esponja": "esponja",
  "esponjas": "esponges",
  "borla": "borla",
  "borlas": "borles",
  "lápiz": "llapis",
  "lápices": "llapis",
  "máscara": "màscara",
  "máscaras": "màscares",
  "fondo": "fons",
  "fondos": "fons",
  "corrector": "corrector",
  "correctores": "correctors",
  "corrección": "correcció",
  "correcciones": "correccions",
  "visagismo": "visatgisme",
  "fantasía": "fantasia",
  "boceto": "esbós",
  "bocetos": "esbossos",
  "dibujo": "dibuix",
  "dibujos": "dibuixos",
  "línea": "línia",
  "líneas": "línies",
  "forma": "forma",
  "formas": "formes",
  "color": "color",
  "colores": "colors",

  // Adjectives
  "correcto": "correcte",
  "correcta": "correcta",
  "correctos": "correctes",
  "correctas": "correctes",
  "incorrecto": "incorrecte",
  "incorrecta": "incorrecta",
  "incorrectos": "incorrectes",
  "incorrectas": "incorrectes",
  "adecuado": "adequat",
  "adecuada": "adequada",
  "adecuados": "adequats",
  "adecuadas": "adequades",
  "inadecuado": "inadequat",
  "inadecuada": "inadequada",
  "inadecuados": "inadequats",
  "inadecuadas": "inadequades",
  "apto": "apte",
  "apta": "apta",
  "aptos": "aptes",
  "aptas": "aptes",
  "bueno": "bo",
  "buena": "bona",
  "buenos": "bons",
  "buenas": "bones",
  "malo": "dolent",
  "mala": "dolenta",
  "malos": "dolents",
  "malas": "dolentes",
  "seguro": "segur",
  "segura": "segura",
  "seguros": "segurs",
  "seguras": "segures",
  "peligroso": "perillós",
  "peligrosa": "perillosa",
  "peligrosos": "perillosos",
  "peligrosas": "perilloses",
  "limpio": "net",
  "limpia": "neta",
  "limpios": "nets",
  "limpias": "netes",
  "sucio": "brut",
  "sucia": "bruta",
  "sucios": "bruts",
  "sucias": "brutes",
  "claro": "clar",
  "clara": "clara",
  "claros": "clars",
  "claras": "clares",
  "oscuro": "fosc",
  "oscura": "fosca",
  "oscuros": "foscos",
  "oscuras": "fosques",
  "breve": "breu",
  "breves": "breus",
  "largo": "llarg",
  "larga": "llarga",
  "largos": "llargs",
  "largas": "llargues",
  "corto": "curt",
  "corta": "curta",
  "cortos": "curts",
  "cortas": "curtes",
  "fácil": "fàcil",
  "fáciles": "fàcils",
  "difícil": "difícil",
  "difíciles": "difícils",
  "sencillo": "senzill",
  "sencilla": "senzilla",
  "sencillos": "senzills",
  "sencillas": "senzilles",
  "complejo": "complex",
  "compleja": "complexa",
  "complejos": "complexos",
  "complejas": "complexes",
  "rápido": "ràpid",
  "rápida": "ràpida",
  "rápidos": "ràpids",
  "rápidas": "ràpides",
  "lento": "lent",
  "lenta": "lenta",
  "lentos": "lents",
  "lentas": "lentes",
  "nuevo": "nou",
  "nueva": "nova",
  "nuevos": "nous",
  "nuevas": "noves",
  "viejo": "vell",
  "vieja": "vella",
  "viejos": "vells",
  "viejas": "velles",
  "antiguo": "antic",
  "antigua": "antiga",
  "antiguos": "antics",
  "antiguas": "antigues",
  "moderno": "modern",
  "moderna": "moderna",
  "modernos": "moderns",
  "modernas": "modernes",
  "real": "real",
  "reales": "reals",
  "ficticio": "fictici",
  "ficticia": "fictícia",
  "ficticios": "ficticis",
  "ficticias": "fictícies",
  "simulado": "simulat",
  "simulada": "simulada",
  "simulados": "simulats",
  "simuladas": "simulades",
  "húmedo": "humit",
  "húmeda": "humida",
  "húmedos": "humits",
  "húmedas": "humides",
  "seco": "sec",
  "seca": "seca",
  "secos": "secs",
  "secas": "seques",
  "mojado": "mullat",
  "mojada": "mullada",
  "mojados": "mullats",
  "mojadas": "mullades",
  "caliente": "calent",
  "calientes": "calents",
  "tibio": "tèbi",
  "tibia": "tèbia",
  "tibios": "tèbis",
  "tibias": "tèbies",
  "frío": "fred",
  "fría": "freda",
  "fríos": "freds",
  "frías": "fredes",
  "líquido": "líquid",
  "líquida": "líquida",
  "líquidos": "líquids",
  "líquidas": "líquides",
  "sólido": "sòlid",
  "sólida": "sòlida",
  "sólidos": "sòlids",
  "sólidas": "sòlides",

  // Verbs (common conjugated forms & infinitives)
  "observa": "observa",
  "observan": "observen",
  "observar": "observar",
  "prepara": "prepara",
  "preparan": "preparen",
  "preparar": "preparar",
  "calcula": "calcula",
  "calculan": "calculen",
  "calcular": "calcular",
  "diseña": "dissenya",
  "diseñan": "dissenyen",
  "diseñar": "dissenyar",
  "elige": "tria",
  "eligen": "trien",
  "elegir": "triar",
  "selecciona": "selecciona",
  "seleccionan": "seleccionen",
  "seleccionar": "seleccionar",
  "realiza": "realitza",
  "realizan": "realitzen",
  "realizar": "realitzar",
  "aplica": "aplica",
  "aplican": "apliquen",
  "aplicar": "aplicar",
  "identifica": "identifica",
  "identifican": "identifiquen",
  "identificar": "identificar",
  "describe": "descriu",
  "describen": "descriuen",
  "describir": "descriure",
  "explica": "explica",
  "explican": "expliquen",
  "explicar": "explicar",
  "analiza": "analitza",
  "analizan": "analitzen",
  "analizar": "analitzar",
  "comprueba": "comprova",
  "comprueban": "comproven",
  "comprobar": "comprovar",
  "presenta": "presenta",
  "presentan": "presenten",
  "presentar": "presentar",
  "utiliza": "utilitza",
  "utilizan": "utilitzen",
  "utilizar": "utilitzar",
  "elabora": "elabora",
  "elaboran": "elaboren",
  "elaborar": "elaborar",
  "crea": "crea",
  "crean": "creen",
  "crear": "crear",
  "construye": "construeix",
  "construyen": "construeixen",
  "construir": "construir",
  "completa": "completa",
  "completan": "completen",
  "completar": "completar",
  "recoge": "recull",
  "recogen": "recollen",
  "recoger": "recollir",
  "practica": "practica",
  "practican": "practiquen",
  "practicar": "practicar",
  "simula": "simula",
  "simulan": "simulen",
  "simular": "simular",
  "organiza": "organitza",
  "organizan": "organitzen",
  "organizar": "organitzar",
  "limpia": "neteja",
  "limpian": "netegen",
  "limpiar": "netejar",
  "desinfecta": "desinfecta",
  "desinfectan": "desinfecten",
  "desinfectar": "desinfectar",
  "lava": "renta",
  "lavan": "renten",
  "lavar": "rentar",
  "seca": "asseca",
  "secan": "assequen",
  "secar": "assecar",
  "peina": "pentina",
  "peinan": "pentinen",
  "peinar": "pentinar",
  "corta": "talla",
  "cortan": "tallen",
  "cortar": "tallar",
  "maquilla": "maquilla",
  "maquillan": "maquillen",
  "maquillar": "maquillar",
  "depila": "depila",
  "depilan": "depilen",
  "depilar": "depilar",
  "decolora": "decolora",
  "decoloran": "decoloren",
  "decolorar": "decolorar",
  "esmalta": "esmalta",
  "esmaltan": "esmalten",
  "esmaltar": "esmaltar",
  "llima": "llima",
  "lliman": "llimen",
  "llimar": "llimar",
  "pule": "puleix",
  "pulen": "puleixen",
  "pulir": "polir",
  "masajea": "fa massatge",
  "masajean": "fan massatge",
  "masajear": "fer massatge",
  "tiñe": "tenyeix",
  "tiñen": "tenyeixen",
  "teñir": "tenyir",
  "colorea": "acoloreix",
  "colorean": "acoloreixen",
  "colorear": "acolorir",
  "cambia": "canvia",
  "cambian": "canvien",
  "cambiar": "canviar",
  "permite": "permet",
  "permiten": "permeten",
  "permitir": "permetre",
  "ayuda": "ajuda",
  "ayudan": "ajuden",
  "ayudar": "ajudar",
  "facilita": "facilita",
  "facilitan": "faciliten",
  "facilitar": "facilitar",
  "aporta": "aporta",
  "aportan": "aporten",
  "aportar": "aportar",
  "conecta": "connecta",
  "conectan": "connecten",
  "conectar": "connectar",
  "relaciona": "relaciona",
  "relacionan": "relacionen",
  "relacionar": "relacionar",
  "vincula": "vincula",
  "vinculan": "vinculen",
  "vincular": "vincular",
  "revisa": "revisa",
  "revisan": "revisen",
  "revisar": "revisar",
  "valora": "valora",
  "valoran": "valoren",
  "valorar": "valorar",
  "defiende": "defén",
  "defienden": "defensen",
  "defender": "defensar",
  "discute": "debat",
  "discuten": "debaten",
  "discutir": "debatre",
  "investiga": "investiga",
  "investigan": "investiguen",
  "investigar": "investigar",
  "busca": "busca",
  "buscan": "busquen",
  "buscar": "buscar",
  "encuentra": "troba",
  "encuentran": "troben",
  "encontrar": "trobar",
  "comparte": "comparteix",
  "comparten": "comparteixen",
  "compartir": "compartir",
  "colabora": "col·labora",
  "colaboran": "col·laboren",
  "colaborar": "col·laborar",
  "participa": "participa",
  "participan": "participen",
  "participar": "participar",
  "atiende": "atén",
  "atienden": "atenen",
  "atender": "atendre",
  "escucha": "escolta",
  "escuchan": "escolten",
  "escuchar": "escoltar",
  "pregunta": "pregunta",
  "preguntan": "pregunten",
  "preguntar": "preguntar",
  "responde": "respon",
  "responden": "responen",
  "responder": "respondre",
  "informa": "informa",
  "informan": "informen",
  "informar": "informar",
  "comunica": "comunica",
  "comunican": "comuniquen",
  "comunicar": "comunicar",
  "escribe": "escriu",
  "escriben": "escriuen",
  "escribir": "escriure",
  "lee": "llegeix",
  "leen": "llegeixen",
  "leer": "llegir",
  "registra": "registra",
  "registran": "registren",
  "registrar": "registrar",
  "recuerda": "recorda",
  "recuerdan": "recorden",
  "recordar": "recordar",
  "aprende": "aprén",
  "aprenden": "aprenen",
  "aprender": "aprendre",
  "enseña": "ensenya",
  "enseñan": "ensenyen",
  "enseñar": "ensenyar",
  "muestra": "mostra",
  "muestran": "mostren",
  "mostrar": "mostrar",
  "demuestra": "demostra",
  "demuestran": "demostren",
  "demostrar": "demostrar",
  "sabe": "sap",
  "saben": "saben",
  "saber": "saber",
  "conoce": "coneix",
  "conocen": "coneixen",
  "conocer": "conéixer",
  "entiende": "entén",
  "entienden": "entenen",
  "entender": "entendre",
  "comprende": "comprén",
  "comprenden": "comprenen",
  "comprender": "comprendre",
  "puede": "pot",
  "pueden": "poden",
  "poder": "poder",
  "debe": "ha de",
  "deben": "han de",
  "deber": "haver de",
  "tiene": "té",
  "tienen": "tenen",
  "tener": "tindre",
  "hay": "hi ha",
  "había": "hi havia",
  "habrá": "hi haurà",
  "hace": "fa",
  "hacen": "fan",
  "hacer": "fer",
  "hecho": "fet",
  "es": "és",
  "son": "són",
  "era": "era",
  "eran": "eren",
  "fue": "va ser",
  "fueron": "van ser",
  "ser": "ser",
  "sido": "estat",
  "está": "està",
  "están": "estan",
  "estaba": "estava",
  "estaban": "estaven",
  "estuvo": "va estar",
  "estuvieron": "van estar",
  "estar": "estar",
  "estado": "estat",
  "da": "dóna",
  "dan": "donen",
  "dar": "donar",
  "dado": "donat",
  "va": "va",
  "van": "van",
  "ir": "anar",
  "ido": "anat",
  "viene": "ve",
  "vienen": "vénen",
  "venir": "vindre",
  "venido": "vingut"
};

function translateText(text) {
  if (!text || typeof text !== 'string') return text;
  let res = text;

  // 1. Multi-word phrase replacements
  for (const [re, rep] of PHRASE_REPLACEMENTS) {
    res = res.replace(re, rep);
  }

  // 2. Word by word replacement with boundary checks & casing preservation
  // We tokenize by keeping delimiters
  const tokens = res.split(/([a-zA-ZáéíóúñüÁÉÍÓÚÑÜ]+)/);
  for (let i = 1; i < tokens.length; i += 2) {
    const word = tokens[i];
    const lower = word.toLowerCase();
    if (WORD_MAP[lower]) {
      let replacement = WORD_MAP[lower];
      // preserve TitleCase / UPPERCASE
      if (word === word.toUpperCase() && word.length > 1) {
        replacement = replacement.toUpperCase();
      } else if (word[0] === word[0].toUpperCase()) {
        replacement = replacement[0].toUpperCase() + replacement.slice(1);
      }
      tokens[i] = replacement;
    } else {
      // Common regular suffixes
      if (lower.endsWith("ción")) {
        tokens[i] = word.slice(0, -4) + (word[0] === word[0].toUpperCase() ? "ció" : "ció");
      } else if (lower.endsWith("ciones")) {
        tokens[i] = word.slice(0, -6) + (word[0] === word[0].toUpperCase() ? "cions" : "cions");
      } else if (lower.endsWith("sión")) {
        tokens[i] = word.slice(0, -4) + (word[0] === word[0].toUpperCase() ? "sió" : "sió");
      } else if (lower.endsWith("siones")) {
        tokens[i] = word.slice(0, -6) + (word[0] === word[0].toUpperCase() ? "sions" : "sions");
      } else if (lower.endsWith("dad")) {
        tokens[i] = word.slice(0, -3) + (word[0] === word[0].toUpperCase() ? "tat" : "tat");
      } else if (lower.endsWith("dades")) {
        tokens[i] = word.slice(0, -5) + (word[0] === word[0].toUpperCase() ? "tats" : "tats");
      } else if (lower.endsWith("mente")) {
        tokens[i] = word.slice(0, -5) + (word[0] === word[0].toUpperCase() ? "ment" : "ment");
      } else if (lower.endsWith("miento")) {
        tokens[i] = word.slice(0, -6) + (word[0] === word[0].toUpperCase() ? "ment" : "ment");
      } else if (lower.endsWith("mientos")) {
        tokens[i] = word.slice(0, -7) + (word[0] === word[0].toUpperCase() ? "ments" : "ments");
      } else if (lower.endsWith("able") || lower.endsWith("ables") || lower.endsWith("ible") || lower.endsWith("ibles")) {
        // identical in Catalan
      } else if (lower.endsWith("ado")) {
        tokens[i] = word.slice(0, -3) + "at";
      } else if (lower.endsWith("ada")) {
        tokens[i] = word.slice(0, -3) + "ada";
      } else if (lower.endsWith("ados")) {
        tokens[i] = word.slice(0, -4) + "ats";
      } else if (lower.endsWith("adas")) {
        tokens[i] = word.slice(0, -4) + "ades";
      } else if (lower.endsWith("ando")) {
        tokens[i] = word.slice(0, -4) + "ant";
      } else if (lower.endsWith("iendo")) {
        tokens[i] = word.slice(0, -5) + "int";
      }
    }
  }
  res = tokens.join('');

  // 3. Catalan orthographic cleanups (Apostrophization & Contractions)
  // de + [aeiouh] -> d'
  res = res.replace(/\bde\s+([aeiouhAEIOUHÀÈÉÍÒÓÚàèéíòóú])/g, "d'$1");
  res = res.replace(/\bDe\s+([aeiouhAEIOUHÀÈÉÍÒÓÚàèéíòóú])/g, "D'$1");
  // a + el -> al
  res = res.replace(/\ba\s+el\b/g, "al");
  res = res.replace(/\bA\s+el\b/g, "Al");
  // a + els -> als
  res = res.replace(/\ba\s+els\b/g, "als");
  res = res.replace(/\bA\s+els\b/g, "Als");
  // de + el -> del
  res = res.replace(/\bde\s+el\b/g, "del");
  res = res.replace(/\bDe\s+el\b/g, "Del");
  // de + els -> dels
  res = res.replace(/\bde\s+els\b/g, "dels");
  res = res.replace(/\bDe\s+els\b/g, "Dels");
  // per + el -> pel
  res = res.replace(/\bper\s+el\b/g, "pel");
  res = res.replace(/\bPer\s+el\b/g, "Pel");
  // per + els -> pels
  res = res.replace(/\bper\s+els\b/g, "pels");
  res = res.replace(/\bPer\s+els\b/g, "Pels");
  // el/la + [aeiouh] -> l'
  res = res.replace(/\bel\s+([aeiouhAEIOUHÀÈÉÍÒÓÚàèéíòóú])/g, "l'$1");
  res = res.replace(/\bEl\s+([aeiouhAEIOUHÀÈÉÍÒÓÚàèéíòóú])/g, "L'$1");
  res = res.replace(/\bla\s+([aeiouAEIOUÀÈÉÍÒÓÚàèéíòóú])/g, "l'$1");
  res = res.replace(/\bLa\s+([aeiouAEIOUÀÈÉÍÒÓÚàèéíòóú])/g, "L'$1");
  // se + [aeiouh] -> s'
  res = res.replace(/\bse\s+([aeiouhAEIOUHÀÈÉÍÒÓÚàèéíòóú])/g, "s'$1");
  res = res.replace(/\bSe\s+([aeiouhAEIOUHÀÈÉÍÒÓÚàèéíòóú])/g, "S'$1");
  // Fix double spaces
  res = res.replace(/\s+/g, ' ').trim();

  return res;
}

module.exports = { translateText, MODULE_NAMES_CA };

// Test with 3 sample activities
const sample = [
  "El grupo observa ejemplos de imagen profesional correcta e incorrecta, mediante fotografías simuladas o casos descritos.",
  "el alumnado crea una guía visual que podría estar en el vestuario o entrada del aula-taller. Objetivo: identificar la imagen personal adecuada para trabajar en peluquería y estética: higiene, uniforme, calzado, cabello, manos, uñas, postura y actitud. Desarrollo: | formato carrusel de Instagram o póster tipo “Get ready with me profesional”, pero sin frivolizar la seguridad. Producto final: manual visual de imagen profesional. Evaluación: claridad, rigor, presentación, lenguaje inclusivo, relación con seguridad e higiene.",
  "Instrucciones visuales, apoyos pautados y trabajo en parejas.",
  "Rúbrica visual y producto de evaluación formativa."
];

console.log("=== TRANSLATION SAMPLES ===");
sample.forEach(s => {
  console.log("ES:", s);
  console.log("CA:", translateText(s));
  console.log("---");
});
