module.exports = {
  "guion": "guió", "guiones": "guions",
  "itinerario": "itinerari", "itinerarios": "itineraris",
  "protocolo": "protocol", "protocolos": "protocols",
  "desarrollo": "desenvolupament",
  "inglés": "anglés", "inglesa": "anglesa", "ingleses": "anglesos", "inglesas": "angleses",
  "sencillo": "senzill", "sencilla": "senzilla", "sencillos": "senzills", "sencillas": "senzilles",
  "pictograma": "pictograma", "pictogramas": "pictogrames",
  "icono": "icona", "iconos": "icones",
  "trato": "tracte",
  "hábito": "hàbit", "hábitos": "hàbits",
  "semáforo": "semàfor", "semáforos": "semàfors",
  "ensayo": "assaig", "ensayos": "assajos",
  "campaña": "campanya", "campañas": "campanyes",
  "boceto": "esbós", "bocetos": "esbossos",
  "resumen": "resum", "resúmenes": "resums",
  "orden": "ordre",
  "evento": "esdeveniment", "eventos": "esdeveniments",
  "tipo": "tipus", "tipos": "tipus",
  "reflexión": "reflexió", "reflexiones": "reflexions",
  "investigar": "investigar", "investiga": "investiga", "investigan": "investiguen", "investigado": "investigat",
  "empleo": "ocupació", "empleabilidad": "ocupabilitat",
  "análisis": "anàlisi",
  "aparato": "aparell", "aparatos": "aparells",
  "infografía": "infografia", "infografías": "infografies",
  "ciencia": "ciència", "ciencias": "ciències",
  "interno": "intern", "interna": "interna", "internos": "interns", "internas": "internes",
  "código": "codi", "códigos": "codis",
  "tarea": "tasca", "tareas": "tasques",
  "tendencia": "tendència", "tendencias": "tendències",
  "gestión": "gestió",
  "búsqueda": "cerca", "búsquedas": "cerques",
  "método": "mètode", "métodos": "mètodes",
  "formato": "format", "formatos": "formats",
  "diseño": "disseny", "diseños": "dissenys",
  "representar": "representar", "representa": "representa", "representan": "representen", "representado": "representat",
  "reparto": "repartiment",
  "hoja": "full", "hojas": "fulls",
  "zona": "zona", "zonas": "zones",
  "breve": "breu", "breves": "breus",
  "respetuoso": "respectuós", "respetuosa": "respectuosa", "respetuosos": "respectuosos", "respetuosas": "respectuoses",
  "armonía": "harmonia",
  "efecto": "efecte", "efectos": "efectes",
  "galería": "galeria", "galerías": "galeries",
  "causa": "causa", "causas": "causes",
  "proceso": "procés", "procesos": "processos",
  "hipótesis": "hipòtesi",
  "obra": "obra", "obras": "obres",
  "decálogo": "decàleg", "decálogos": "decàlegs",
  "competencial": "competencial", "competenciales": "competencials",
  "resto": "resta",
  "laboratorio": "laboratori", "laboratorios": "laboratoris",
  "calculadora": "calculadora", "calculadoras": "calculadores",
  "estereotipo": "estereotip", "estereotipos": "estereotips",
  "pista": "pista", "pistas": "pistes",
  "cierre": "tancament", "cierres": "tancaments",
  "permanente": "permanent", "permanentes": "permanents",
  "menú": "menú", "menús": "menús",
  "mural": "mural", "murales": "murals",
  "auditoría": "auditoria", "auditorías": "auditories",
  "glosario": "glosari", "glosarios": "glosaris",
  "toma": "presa", "tomas": "preses",
  "marca": "marca", "marcas": "marques",
  "inventario": "inventari", "inventarios": "inventaris",
  "tecnología": "tecnologia", "tecnologías": "tecnologies",
  "auxiliar": "auxiliar", "auxiliares": "auxiliars",
  "coevaluación": "coavaluació", "autoevaluación": "autoavaluació",
  "posibilidad": "possibilitat", "posibilidades": "possibilitats",
  "fuerza": "força", "fuerzas": "forces",
  "repetición": "repetició", "repeticiones": "repeticions",
  "segundo": "segon", "segundos": "segons",
  "ventaja": "avantatge", "ventajas": "avantatges",
  "inconveniente": "inconvenient", "inconvenientes": "inconvenients",
  "dibujo": "dibuix", "dibujos": "dibuixos",
  "límite": "límit", "límites": "límits",
  "estación": "estació", "estaciones": "estacions",
  "superficie": "superfície", "superficies": "superfícies",
  "ayuda": "ajuda", "ayudas": "ajudes",
  "eficiencia": "eficiència",
  "pausa": "pausa", "pausas": "pauses",
  "catálogo": "catàleg", "catálogos": "catàlegs",
  "estrategia": "estratègia", "estrategias": "estratègies",
  "representación": "representació",
  "cortesía": "cortesia",
  "maniobra": "maniobra", "maniobras": "maniobres",
  "necesidad": "necessitat", "necesidades": "necessitats",
  "cosmética": "cosmètica", "cosmético": "cosmètic", "cosméticos": "cosmètics",
  "escritura": "escriptura",
  "temporal": "temporal", "temporales": "temporals",
  "consejo": "consell", "consejos": "consells",
  "bandeja": "safata", "bandejas": "safates",
  "advertencia": "advertència", "advertencias": "advertències",
  "distancia": "distància", "distancias": "distàncies",
  "confirmación": "confirmació", "confirmaciones": "confirmacions",
  "ingrediente": "ingredient", "ingredientes": "ingredients",
  "capacidad": "capacitat", "capacidades": "capacitats",
  "voz": "veu", "voces": "veus",
  "alteración": "alteració", "alteraciones": "alteracions",
  "arte": "art", "artes": "arts",
  "pasaporte": "passaport", "pasaportes": "passaports",
  "tema": "tema", "temas": "temes",
  "corrección": "correcció", "correcciones": "correccions",
  "tensión": "tensió", "tensiones": "tensions",
  "desafío": "desafiament", "desafíos": "desafiaments",
  "parte": "part", "partes": "parts",
  "insignia": "insígnia", "insignias": "insígnies",
  "experiencia": "experiència", "experiencias": "experiències",
  "reducción": "reducció",
  "común": "comú", "comunes": "comuns",
  "falta": "manca", "faltas": "manques",
  "precaución": "precaució", "precauciones": "precaucions",
  "soporte": "suport", "soportes": "suports",
  "votación": "votació", "votaciones": "votacions",
  "luz": "llum", "luces": "llums",
  "simetría": "simetria",
  "resolución": "resolució",
  "materia": "matèria", "materias": "matèries",
  "parcial": "parcial", "parciales": "parcials",
  "neutralización": "neutralització",
  "promoción": "promoció", "promociones": "promocions",
  "lineal": "lineal", "lineales": "lineals",
  "relieve": "relleu", "relieves": "relleus",
  "cuestionario": "qüestionari", "cuestionarios": "qüestionaris",
  "autoevaluativo": "autoavaluatiu", "autoevaluativa": "autoavaluativa",
  "frecuencia": "freqüència", "frecuencias": "freqüències",
  "secuencia": "seqüència", "secuencias": "seqüències",
  "secuenciado": "seqüenciat", "secuenciada": "seqüenciada",
  "exposición": "exposició", "exposiciones": "exposicions",
  "demostración": "demostració", "demostraciones": "demostracions",
  "diferenciación": "diferenciació",
  "adecuación": "adequació",
  "asociación": "associació",
  "interpretación": "interpretació",
  "aplicabilidad": "aplicabilitat",
  "coordinación": "coordinació",
  "participación": "participació",
  "colaboración": "col·laboració",
  "interacción": "interacció",
  "justificación": "justificació", "justificaciones": "justificacions",
  "clasificación": "classificació", "clasificaciones": "classificacions",
  "valoración": "valoració", "valoraciones": "valoracions",
  "presentación": "presentació", "presentaciones": "presentacions",
  "introducción": "introducció",
  "definición": "definició", "definiciones": "definicions",
  "organización": "organització",
  "localización": "localització",
  "reutilización": "reutilització",
  "utilización": "utilització",
  "manipulación": "manipulació",
  "simulación": "simulació", "simulaciones": "simulacions",
  "elaboración": "elaboració",
  "planificación": "planificació",
  "verificación": "verificació",
  "comprobación": "comprovació",
  "conservación": "conservació",
  "desinfección": "desinfecció",
  "esterilización": "esterilització",
  "orientación": "orientació",
  "atribución": "atribució",
  "distribución": "distribució",
  "contribución": "contribució",
  "resolución": "resolució",
  "conclusión": "conclusió", "conclusiones": "conclusions",
  "decisión": "decisió", "decisiones": "decisions",
  "precisión": "precisió",
  "revisión": "revisió", "revisiones": "revisions",
  "supervisión": "supervisió",
  "previsión": "previsió", "previsiones": "previsions",
  "emisión": "emissió", "emisiones": "emissions",
  "transmisión": "transmissió",
  "comprensión": "comprensió",
  "extensión": "extensió",
  "dimensión": "dimensió", "dimensiones": "dimensions",
  "ilusión": "il·lusió",
  "versión": "versió", "versiones": "versions",
  "sesión": "sessió", "sesiones": "sessions",
  "presión": "pressió"
};
