module.exports = {
  "uso": "ús", "usos": "úsos",
  "vocabulario": "vocabulari", "vocabularios": "vocabularis",
  "comprender": "comprendre", "comprende": "comprén", "comprenden": "comprenen",
  "estilo": "estil", "estilos": "estils",
  "plan": "pla", "planes": "plans",
  "ergonomía": "ergonomia",
  "panel": "panell", "paneles": "panells",
  "registran": "registren",
  "mejoras": "millores",
  "línea": "línia", "líneas": "línies",
  "rostro": "rostre", "rostros": "rostres",
  "preferencias": "preferències",
  "completan": "completen",
  "espacio": "espai", "espacios": "espais",
  "contexto": "context", "contextos": "contexts",
  "clave": "clau", "claves": "claus",
  "extraen": "extrauen",
  "transporte": "transport",
  "proyecto": "projecte", "proyectos": "projectes",
  "reducir": "reduir", "reduce": "reduïx", "reducen": "reduïxen",
  "verde": "verd", "verdes": "verds",
  "formas": "formes",
  "iniciadoras": "iniciadores",
  "futuro": "futur", "futuros": "futurs",
  "árbol": "arbre", "árboles": "arbres",
  "saludo": "salutació", "saludos": "salutacions",
  "aceite": "oli", "aceites": "olis",
  "conclusiones": "conclusions",
  "cerradas": "tancades", "cerrado": "tancat", "cerrada": "tancada", "cerrados": "tancats",
  "abierto": "obert", "abierta": "oberta", "abiertos": "oberts", "abiertas": "obertes",
  "segundas": "segones",
  "estaciones": "estacions",
  "tintes": "tints",
  "seleccionan": "seleccionen",
  "relacionan": "relacionen",
  "escriben": "escriuen",
  "agrario": "agrari", "agrarios": "agraris",
  "hacen": "fan",
  "derivar": "derivar", "deriva": "deriva", "derivan": "deriven",
  "transformar": "transformar", "transforman": "transformen",
  "ojos": "ulls",
  "buscan": "busquen",
  "extranjero": "estranger", "extranjera": "estrangera", "extranjeros": "estrangers", "extranjeras": "estrangeres",
  "caducidad": "caducitat",
  "viral": "viral", "virales": "virals",
  "esperado": "esperat", "esperada": "esperada", "esperados": "esperats", "esperadas": "esperades",
  "influyen": "influïxen", "influye": "influïx",
  "redondeo": "arredoniment",
  "diferenciar": "diferenciar", "diferencia": "diferencia", "diferencian": "diferencien",
  "recogen": "recollen",
  "siguen": "seguixen",
  "perder": "perdre",
  "posturas": "postures",
  "simulan": "simulen",
  "pueden": "poden",
  "rojo": "roig", "roja": "roja", "rojos": "rojos", "rojas": "roges",
  "blanco": "blanc", "blanca": "blanca", "blancos": "blancs", "blancas": "blanques",
  "negro": "negre", "negra": "negra", "negros": "negres", "negras": "negres",
  "azul": "blau", "azules": "blaus",
  "amarillo": "groc", "amarilla": "groga", "amarillos": "grocs", "amarillas": "grogues",
  "castaño": "castany", "castaña": "castanya", "castaños": "castanys", "castañas": "castanyes",
  "rubio": "ros", "rubia": "rossa", "rubios": "rossos", "rubias": "rosses",
  "previsibles": "previsibles",
  "cantidades": "quantitats",
  "acuerdos": "acords",
  "organizar": "organitzar", "organizan": "organitzen",
  "público": "públic", "pública": "pública", "públicos": "públics", "públiques": "públiques",
  "dibujan": "dibuixen",
  "evitar": "evitar", "evitan": "eviten",
  "escuchar": "escoltar", "escuchan": "escolten",
  "vincula": "vincula", "vinculan": "vinculen",
  "ayudan": "ajuden",
  "ordenan": "ordenen",
  "reunión": "reunió", "reuniones": "reunions",
  "bandas": "bandes",
  "cortas": "curtes",
  "defensa": "defensa",
  "confidencialidad": "confidencialitat",
  "aporta": "aporta", "aportan": "aporten",
  "página": "pàgina", "páginas": "pàgines",
  "conectan": "connecten",
  "semana": "setmana", "semanas": "setmanes",
  "detectan": "detecten",
  "acciones": "accions",
  "movimiento": "moviment", "movimientos": "moviments",
  "literario": "literari", "literarios": "literaris",
  "herramientas": "eines", "herramienta": "eina",
  "dificultad": "dificultat", "dificultades": "dificultats",
  "verbal": "verbal", "verbales": "verbals",
  "recibir": "rebre",
  "atractivo": "atractiu", "atractiva": "atractiva", "atractivos": "atractius", "atractivas": "atractives",
  "detectives": "detectius", "detective": "detectiu",
  "fantasía": "fantasia",
  "espera": "espera",
  "alternativas": "alternatives",
  "precaución": "precaució", "precauciones": "precaucions",
  "mechas": "metxes",
  "gráficas": "gràfiques",
  "espátulas": "espàtules",
  "han": "han",
  "cálculos": "càlculs",
  "respetuosas": "respectuoses",
  "asumen": "assumeixen",
  "pasos": "pasos",
  "técnicas": "tècniques",
  "autonomía": "autonomia",
  "fórmulas": "fórmules", "fórmula": "fórmula",
  "deberes": "deures",
  "juegos": "jocs",
  "respetando": "respectant",
  "cuidado": "cura", "cuidados": "cures",
  "practican": "practiquen",
  "historia": "història",
  "conversación": "conversa", "conversaciones": "converses",
  "conecta": "connecta",
  "expectativas": "expectatives",
  "practicar": "practicar",
  "relacionar": "relacionar",
  "encuesta": "enquesta", "encuestas": "enquestes",
  "envases": "envasos",
  "observan": "observen",
  "adaptación": "adaptació",
  "calcular": "calcular",
  "resolver": "resoldre",
  "publicidad": "publicitat",
  "reclamaciones": "reclamacions",
  "reclamación": "reclamació",
  "ejemplo": "exemple", "ejemplos": "exemples",
  "dirección": "direcció",
  "simular": "simular",
  "interpretación": "interpretació",
  "investigan": "investiguen",
  "recogida": "recollida",
  "calculan": "calculen",
  "actuación": "actuació", "actuaciones": "actuacions",
  "puntualidad": "puntualitat",
  "día": "dia", "días": "dies",
  "responder": "respondre",
  "redactar": "redactar",
  "identifican": "identifiquen",
  "profesión": "professió",
  "proponen": "proposen",
  "citas": "cites",
  "minutos": "minuts",
  "tablas": "taules",
  "ficticios": "ficticis", "ficticias": "fictícies",
  "creatividad": "creativitat",
  "comodidad": "comoditat",
  "esmaltes": "esmalts",
  "rostro": "rostre",
  "aplicar": "aplicar",
  "respuestas": "respostes",
  "pies": "peus",
  "vello": "pèl",
  "espacio": "espai",
  "unidades": "unitats",
  "leer": "llegir",
  "precisión": "precisió",
  "observar": "observar",
  "cromático": "cromàtic", "cromática": "cromàtica",
  "clasifican": "classifiquen",
  "acabado": "acabat", "acabada": "acabada", "acabados": "acabats", "acabadas": "acabades",
  "explica": "explica",
  "deciden": "decidixen",
  "gráfico": "gràfic", "gráficos": "gràfics",
  "conectar": "connectar",
  "privacidad": "privadesa",
  "comunicar": "comunicar",
  "pensamiento": "pensament", "pensamientos": "pensaments",
  "problemas": "problemes",
  "preguntar": "preguntar",
  "escala": "escala", "escalas": "escales",
  "graduación": "graduació",
  "revisar": "revisar",
  "decidir": "decidir",
  "reciclaje": "reciclatge",
  "hasta": "fins a",
  "adaptar": "adaptar",
  "eligen": "trien",
  "indicadores": "indicadors",
  "glosario": "glosari",
  "informes": "informes",
  "procesos": "processos"
};
